

;###########################################################################
.pattern.table
  .dw .pattern.table.chan0
  .dw .pattern.table.chan1
  .dw .pattern.table.chan2
  .dw .pattern.table.chan3
  .dw .pattern.table.chan4
  .dw .pattern.table.chan5


;.....................................................
.pattern.table.chan0
  .dw .pattern.table.chan0.pattern0
  .dw .pattern.table.chan0.pattern1
  .dw .pattern.table.chan0.pattern2
  .dw .pattern.table.chan0.pattern3
  .dw .pattern.table.chan0.pattern4
  .dw .pattern.table.chan0.pattern5
  .dw .pattern.table.chan0.pattern6
  .dw .pattern.table.chan0.pattern7
  .dw .pattern.table.chan0.pattern8
;.....................................................
.pattern.table.chan1
  .dw .pattern.table.chan1.pattern0
  .dw .pattern.table.chan1.pattern1
  .dw .pattern.table.chan1.pattern2
  .dw .pattern.table.chan1.pattern3
  .dw .pattern.table.chan1.pattern4
  .dw .pattern.table.chan1.pattern5
  .dw .pattern.table.chan1.pattern6
  .dw .pattern.table.chan1.pattern7
  .dw .pattern.table.chan1.pattern8
  .dw .pattern.table.chan1.pattern9
  .dw .pattern.table.chan1.pattern10
  .dw .pattern.table.chan1.pattern11
  .dw .pattern.table.chan1.pattern12
;.....................................................
.pattern.table.chan2
  .dw .pattern.table.chan2.pattern0
  .dw .pattern.table.chan2.pattern1
  .dw .pattern.table.chan2.pattern2
  .dw .pattern.table.chan2.pattern3
  .dw .pattern.table.chan2.pattern4
  .dw .pattern.table.chan2.pattern5
  .dw .pattern.table.chan2.pattern6
  .dw .pattern.table.chan2.pattern7
  .dw .pattern.table.chan2.pattern8
  .dw .pattern.table.chan2.pattern9
  .dw .pattern.table.chan2.pattern10
;.....................................................
.pattern.table.chan3
  .dw .pattern.table.chan3.pattern0
  .dw .pattern.table.chan3.pattern1
  .dw .pattern.table.chan3.pattern2
  .dw .pattern.table.chan3.pattern3
  .dw .pattern.table.chan3.pattern4
  .dw .pattern.table.chan3.pattern5
  .dw .pattern.table.chan3.pattern6
  .dw .pattern.table.chan3.pattern7
  .dw .pattern.table.chan3.pattern8
  .dw .pattern.table.chan3.pattern9
  .dw .pattern.table.chan3.pattern10
  .dw .pattern.table.chan3.pattern11
  .dw .pattern.table.chan3.pattern12
  .dw .pattern.table.chan3.pattern13
;.....................................................
.pattern.table.chan4
  .dw .pattern.table.chan4.pattern0
  .dw .pattern.table.chan4.pattern1
  .dw .pattern.table.chan4.pattern2
  .dw .pattern.table.chan4.pattern3
  .dw .pattern.table.chan4.pattern4
  .dw .pattern.table.chan4.pattern5
  .dw .pattern.table.chan4.pattern6
;.....................................................
.pattern.table.chan5
  .dw .pattern.table.chan5.pattern0
  .dw .pattern.table.chan5.pattern1
  .dw .pattern.table.chan5.pattern2
  .dw .pattern.table.chan5.pattern3
  .dw .pattern.table.chan5.pattern4


;###########################################################################


;........................................................................
;........................................................................

;......................................
.pattern.table.chan0.pattern0

  .db $3d, $4, $6, $1f, $10, $2
  .db $e2
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $13, $6, $1f
  .db $e4
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $2, $6
  .db $30, $ec, $5
  .db $5, $4, $6
  .db $e4
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $5
  .db $d, $6, $6, $1f
  .db $30, $ec, $6
  .db $5, $7, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $30, $ec, $6
  .db $5, $d, $6
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $30, $ec, $6
  .db $5, $6, $6
  .db $e2
  .db $30, $ec, $5


;......................................
.pattern.table.chan0.pattern1

  .db $5, $4, $6
  .db $e2
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $13, $6, $1f
  .db $e4
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $2, $6
  .db $30, $ec, $5
  .db $5, $4, $6
  .db $e4
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $5
  .db $d, $9, $6, $1f
  .db $30, $ec, $6
  .db $5, $a, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $30, $ec, $5
  .db $5, $a, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $4
  .db $5, $a, $6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan0.pattern2

  .db $35, $4, $6, $10, $2
  .db $e2
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $13, $6, $1f
  .db $e4
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $e1
  .db $8, $18
  .db $e3
  .db $e0
  .db $e3
  .db $d, $4, $6, $1f
  .db $e2
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $5
  .db $d, $9, $6, $1f
  .db $30, $ec, $6
  .db $5, $a, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $30, $ec, $5
  .db $5, $a, $6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $30, $ec, $4
  .db $5, $a, $6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan0.pattern3

  .db $d, $9, $6, $1f
  .db $e6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $c, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $4, $6
  .db $e4
  .db $30, $ec, $6
  .db $5, $9, $6
  .db $30, $ec, $5
  .db $5, $a, $6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $30, $ec, $6
  .db $5, $7, $6
  .db $30, $ec, $4
  .db $5, $9, $6
  .db $30, $ec, $6
  .db $5, $4, $6
  .db $e2
  .db $30, $ec, $5


;......................................
.pattern.table.chan0.pattern4

  .db $5, $9, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $c, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $4, $6
  .db $e2
  .db $30, $ec, $6
  .db $5, $7, $6
  .db $30, $ec, $5
  .db $5, $6, $6
  .db $30, $ec, $6
  .db $5, $7, $6
  .db $30, $ec, $4
  .db $5, $b, $6
  .db $30, $ec, $6
  .db $5, $4, $6
  .db $30, $ec, $5
  .db $5, $7, $6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $e2
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $e2
  .db $30, $ec, $6
  .db $5, $7, $6
  .db $e2
  .db $30, $ec, $6
  .db $5, $6, $6
  .db $e2
  .db $30, $ec, $5


;......................................
.pattern.table.chan0.pattern5

  .db $5, $9, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $c, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $d, $10, $6, $18
  .db $30, $ec, $6
  .db $d, $10, $6, $1f
  .db $30, $ec, $5
  .db $d, $10, $6, $18
  .db $e2
  .db $30, $ec, $6
  .db $d, $b, $6, $1f
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $6
  .db $d, $10, $6, $18
  .db $e7
  .db $8, $12
  .db $e3
  .db $8, $f
  .db $e3


;......................................
.pattern.table.chan0.pattern6

  .db $3d, $4, $6, $1f, $10, $2
  .db $e2
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $e, $6, $1f
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $e1
  .db $8, $18
  .db $30, $ec, $6
  .db $d, $13, $6, $1f
  .db $e4
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $6
  .db $5, $e, $6
  .db $30, $ec, $4
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $2, $6
  .db $30, $ec, $5
  .db $5, $4, $6
  .db $e1
  .db $8, $18
  .db $eb
  .db $d, $12, $6, $1f
  .db $35, $13, $6, $3, $8
  .db $e1
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $6
  .db $5, $b, $6
  .db $30, $ec, $5
  .db $5, $9, $6
  .db $30, $ec, $5
  .db $5, $7, $6
  .db $30, $ec, $5
  .db $5, $b, $6
  .db $30, $ec, $6
  .db $5, $7, $6
  .db $e2
  .db $30, $ec, $6


;......................................
.pattern.table.chan0.pattern7

  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $15, $6
  .db $30, $ec, $6
  .db $5, $13, $6
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $30, $ec, $6
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $5
  .db $5, $17, $6
  .db $30, $ec, $6
  .db $5, $16, $6
  .db $30, $ec, $4
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $d, $13, $6, $18
  .db $30, $ec, $5
  .db $d, $15, $6, $1f
  .db $30, $ec, $6
  .db $d, $15, $6, $18
  .db $30, $ec, $4
  .db $d, $17, $6, $1f
  .db $30, $ec, $6
  .db $d, $17, $6, $18
  .db $30, $ec, $5
  .db $d, $13, $6, $1f
  .db $30, $ec, $6
  .db $d, $13, $6, $18
  .db $30, $ec, $5
  .db $d, $17, $6, $1f
  .db $30, $ec, $5
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $17, $6
  .db $30, $ec, $6
  .db $5, $15, $6
  .db $30, $ec, $4
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan0.pattern8

  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $15, $6
  .db $30, $ec, $6
  .db $5, $13, $6
  .db $30, $ec, $4
  .db $5, $10, $6
  .db $30, $ec, $6
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $5
  .db $5, $17, $6
  .db $30, $ec, $6
  .db $5, $16, $6
  .db $30, $ec, $4
  .db $5, $15, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $5
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $d, $13, $6, $18
  .db $30, $ec, $5
  .db $d, $15, $6, $1f
  .db $30, $ec, $6
  .db $d, $15, $6, $18
  .db $30, $ec, $4
  .db $d, $17, $6, $1f
  .db $30, $ec, $6
  .db $d, $17, $6, $18
  .db $30, $ec, $5
  .db $d, $1a, $6, $1f
  .db $30, $ec, $6
  .db $d, $1a, $6, $18
  .db $e2
  .db $30, $ec, $5
  .db $d, $10, $6, $1f
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan1.pattern0

  .db $7d, $10, $8, $1b, $10, $3, $3, $e5, $88
  .db $e3
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1f, $8, $1b, $3, $8, $ff
  .db $e1
  .db $30, $4, $64
  .db $e3
  .db $35, $1c, $8, $4, $0
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $5, $e, $8
  .db $e1
  .db $5, $10, $8
  .db $e5
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $12, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $13, $8
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1
  .db $5, $15, $8
  .db $e1
  .db $5, $19, $8
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $5, $10, $8
  .db $35, $10, $8, $ed, $3
  .db $5, $10, $8
  .db $35, $10, $8, $ed, $3


;......................................
.pattern.table.chan1.pattern1

  .db $75, $10, $8, $10, $3, $3, $e5, $88
  .db $e3
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1f, $8, $1b, $3, $8, $ff
  .db $e1
  .db $30, $4, $64
  .db $e3
  .db $35, $1c, $8, $4, $0
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $5, $e, $8
  .db $e1
  .db $5, $10, $8
  .db $e5
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $15, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $16, $8
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $15, $8
  .db $e1
  .db $5, $16, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1
  .db $5, $16, $8
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1


;......................................
.pattern.table.chan1.pattern2

  .db $75, $10, $8, $10, $3, $3, $e5, $88
  .db $e3
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1f, $8, $1b, $3, $8, $ff
  .db $e1
  .db $30, $4, $64
  .db $e3
  .db $35, $1c, $8, $4, $0
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $8, $14
  .db $e7
  .db $d, $10, $8, $1b
  .db $e3
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $15, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $16, $8
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $15, $8
  .db $e1
  .db $5, $16, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1
  .db $5, $16, $8
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1


;......................................
.pattern.table.chan1.pattern3

  .db $3d, $10, $6, $1b, $10, $4
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $6
  .db $5, $17, $6
  .db $30, $ec, $4
  .db $5, $1c, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $e, $6
  .db $30, $ec, $6
  .db $5, $10, $6
  .db $30, $ec, $5
  .db $5, $13, $6
  .db $30, $ec, $5
  .db $5, $17, $6
  .db $30, $ec, $5
  .db $5, $1c, $6
  .db $30, $ec, $6
  .db $5, $1a, $6
  .db $30, $ec, $4
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1e, $6
  .db $30, $ec, $5
  .db $5, $1f, $6
  .db $30, $ec, $6
  .db $5, $21, $6
  .db $e2
  .db $30, $ec, $6
  .db $5, $1f, $6
  .db $30, $ec, $5
  .db $5, $1e, $6
  .db $30, $ec, $6
  .db $5, $23, $6
  .db $30, $ec, $4
  .db $5, $1f, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $23, $6
  .db $30, $ec, $6
  .db $5, $1f, $6
  .db $30, $ec, $5
  .db $5, $21, $6
  .db $30, $ec, $5
  .db $5, $23, $6
  .db $30, $ec, $5
  .db $5, $21, $6
  .db $30, $ec, $6
  .db $5, $1f, $6
  .db $30, $ec, $4
  .db $5, $21, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1e, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan1.pattern4

  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1a, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1f, $6
  .db $30, $ec, $6
  .db $5, $23, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1a, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1f, $6
  .db $30, $ec, $5
  .db $5, $23, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $26, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2a, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $e2
  .db $30, $ec, $6
  .db $5, $1f, $6
  .db $30, $ec, $5
  .db $5, $1c, $6
  .db $30, $ec, $6
  .db $5, $21, $6
  .db $30, $ec, $4
  .db $5, $1c, $6
  .db $e2
  .db $30, $ec, $5
  .db $5, $23, $6
  .db $30, $ec, $6
  .db $5, $21, $6
  .db $30, $ec, $5
  .db $5, $23, $6
  .db $30, $ec, $5
  .db $5, $21, $6
  .db $30, $ec, $5
  .db $5, $22, $6
  .db $30, $ec, $6
  .db $5, $23, $6
  .db $30, $ec, $4
  .db $5, $1f, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $17, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan1.pattern5

  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1a, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1f, $6
  .db $30, $ec, $6
  .db $5, $23, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1a, $6
  .db $30, $ec, $6
  .db $5, $1c, $6
  .db $30, $ec, $5
  .db $5, $1f, $6
  .db $30, $ec, $5
  .db $5, $23, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $26, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2a, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $d, $28, $6, $14
  .db $30, $ec, $6
  .db $d, $28, $6, $1b
  .db $30, $ec, $5
  .db $d, $28, $6, $14
  .db $e2
  .db $30, $ec, $6
  .db $d, $28, $6, $1b
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $d, $28, $6, $14
  .db $e7
  .db $8, $f
  .db $e7


;......................................
.pattern.table.chan1.pattern6

  .db $7d, $10, $8, $1b, $10, $3, $3, $e5, $88
  .db $e3
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1a, $8, $1b, $3, $8, $ff
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $4d, $1c, $8, $14, $3, $8, $df
  .db $e1
  .db $4d, $1f, $8, $1b, $3, $8, $ff
  .db $e1
  .db $30, $4, $64
  .db $e3
  .db $35, $1c, $8, $4, $0
  .db $e1
  .db $5, $17, $8
  .db $e1
  .db $5, $1a, $8
  .db $e1
  .db $5, $1c, $8
  .db $e1
  .db $5, $e, $8
  .db $e1
  .db $5, $10, $8
  .db $fd
  .db $5, $13, $8
  .db $e3


;......................................
.pattern.table.chan1.pattern7

  .db $3d, $2c, $6, $1e, $10, $9
  .db $35, $2e, $6, $3, $1
  .db $e6
  .db $30, $4, $64
  .db $ee
  .db $30, $ec, $6
  .db $35, $2b, $6, $4, $0
  .db $30, $ec, $4
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $32, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $2e, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $4
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $32, $6
  .db $30, $ec, $5
  .db $5, $31, $6
  .db $30, $ec, $6
  .db $5, $2f, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $2a, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $4
  .db $5, $2e, $6
  .db $30, $ec, $6
  .db $5, $2f, $6
  .db $30, $ec, $5
  .db $5, $32, $6
  .db $30, $ec, $6


;......................................
.pattern.table.chan1.pattern8

  .db $5, $34, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $2c, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $4
  .db $5, $2c, $6
  .db $30, $ec, $6
  .db $5, $2f, $6
  .db $30, $ec, $5
  .db $5, $31, $6
  .db $30, $ec, $6
  .db $5, $32, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $31, $6
  .db $30, $ec, $5
  .db $5, $2a, $6
  .db $30, $ec, $6
  .db $5, $2f, $6
  .db $30, $ec, $4
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $35, $31, $6, $3, $f
  .db $35, $2f, $6, $3, $f
  .db $30, $ec, $6
  .db $5, $34, $6
  .db $e6
  .db $30, $ec, $6
  .db $5, $37, $6
  .db $30, $ec, $4
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $38, $6
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $39, $6
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $5
  .db $5, $3a, $6
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $3b, $6
  .db $30, $ec, $4
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $3c, $6
  .db $35, $3e, $6, $3, $1
  .db $e2


;......................................
.pattern.table.chan1.pattern9

  .db $e7
  .db $30, $ec, $6
  .db $5, $3b, $6
  .db $30, $ec, $4
  .db $5, $39, $6
  .db $30, $ec, $6
  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $32, $6
  .db $30, $ec, $5
  .db $5, $39, $6
  .db $30, $ec, $5
  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $32, $6
  .db $30, $ec, $4
  .db $5, $2f, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $32, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $75, $2f, $6, $ec, $3, $3, $ed, $4
  .db $e1
  .db $30, $ec, $6
  .db $5, $30, $6
  .db $30, $ec, $5
  .db $e1
  .db $75, $34, $6, $ec, $7, $3, $ed, $2
  .db $e1
  .db $45, $36, $6, $3, $ed, $4
  .db $e1
  .db $30, $ec, $6
  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $39, $6
  .db $30, $ec, $5
  .db $5, $36, $6
  .db $30, $ec, $5
  .db $5, $32, $6
  .db $30, $ec, $6
  .db $5, $3b, $6
  .db $30, $ec, $4
  .db $5, $36, $6
  .db $30, $ec, $6
  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $36, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan1.pattern10

  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $36, $6
  .db $30, $ec, $6
  .db $5, $37, $6
  .db $e1
  .db $30, $4, $64
  .db $e2
  .db $30, $ec, $4
  .db $35, $39, $6, $4, $0
  .db $30, $ec, $6
  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $37, $6
  .db $35, $39, $6, $3, $8
  .db $e1
  .db $30, $ec, $5
  .db $5, $37, $6
  .db $30, $ec, $5
  .db $5, $36, $6
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $5, $32, $6
  .db $30, $ec, $4
  .db $5, $34, $6
  .db $30, $ec, $5
  .db $5, $36, $6
  .db $30, $ec, $5
  .db $5, $32, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $2e, $6
  .db $30, $ec, $4
  .db $5, $2d, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan1.pattern11

  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $2e, $6
  .db $30, $ec, $4
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $26, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $d, $2b, $6, $18
  .db $30, $ec, $5
  .db $d, $2d, $6, $1e
  .db $30, $ec, $6
  .db $d, $2d, $6, $18
  .db $30, $ec, $4
  .db $d, $2f, $6, $1e
  .db $30, $ec, $6
  .db $d, $2f, $6, $18
  .db $30, $ec, $5
  .db $d, $32, $6, $1e
  .db $30, $ec, $6
  .db $d, $32, $6, $18
  .db $30, $ec, $5
  .db $d, $2f, $6, $1e
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $4
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $26, $6
  .db $30, $ec, $5


;......................................
.pattern.table.chan1.pattern12

  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $6
  .db $5, $2b, $6
  .db $30, $ec, $4
  .db $5, $28, $6
  .db $30, $ec, $6
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $2f, $6
  .db $30, $ec, $6
  .db $5, $2e, $6
  .db $30, $ec, $4
  .db $5, $2d, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $5
  .db $5, $26, $6
  .db $30, $ec, $5
  .db $5, $28, $6
  .db $30, $ec, $5
  .db $5, $2b, $6
  .db $30, $ec, $6
  .db $d, $2b, $6, $18
  .db $30, $ec, $5
  .db $d, $2d, $6, $1e
  .db $30, $ec, $6
  .db $d, $2d, $6, $18
  .db $30, $ec, $4
  .db $d, $2f, $6, $1e
  .db $30, $ec, $6
  .db $d, $2f, $6, $18
  .db $30, $ec, $5
  .db $d, $32, $6, $1e
  .db $30, $ec, $6
  .db $d, $32, $6, $18
  .db $e2
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $e7
  .db $30, $2, $1f
  .db $e3


;........................................................................
;........................................................................

;......................................
.pattern.table.chan2.pattern0

  .db $fe
  .db $fe
  .db $e4


;......................................
.pattern.table.chan2.pattern1

  .db $fe
  .db $fa
  .db $30, $8, $fe
  .db $e3
  .db $35, $13, $9, $10, $6
  .db $e3


;......................................
.pattern.table.chan2.pattern2

  .db $8, $18
  .db $30, $ec, $5
  .db $7d, $10, $9, $1f, $10, $6, $3, $8, $fe
  .db $30, $ec, $6
  .db $5, $13, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $6
  .db $d, $15, $9, $18
  .db $30, $ec, $4
  .db $d, $17, $9, $1f
  .db $30, $ec, $6
  .db $d, $17, $9, $18
  .db $30, $ec, $5
  .db $d, $17, $9, $1f
  .db $30, $ec, $6
  .db $5, $16, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $16, $9
  .db $30, $ec, $5
  .db $5, $17, $9
  .db $30, $ec, $6
  .db $5, $16, $9
  .db $30, $ec, $4
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $16, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $6
  .db $5, $17, $9
  .db $30, $ec, $5
  .db $5, $1a, $9
  .db $30, $ec, $6
  .db $5, $1c, $9
  .db $30, $ec, $5
  .db $5, $10, $9
  .db $e2
  .db $30, $ec, $4
  .db $5, $17, $9
  .db $30, $ec, $6
  .db $5, $1a, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $6
  .db $5, $17, $9
  .db $30, $ec, $5
  .db $5, $1a, $9
  .db $30, $ec, $5
  .db $5, $1e, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $6
  .db $5, $1a, $9
  .db $30, $ec, $4
  .db $5, $1e, $9
  .db $30, $ec, $6
  .db $5, $1f, $9
  .db $30, $ec, $5
  .db $5, $21, $9
  .db $e1


;......................................
.pattern.table.chan2.pattern3

  .db $e1
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $6
  .db $5, $1a, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $6
  .db $d, $1c, $9, $18
  .db $30, $ec, $4
  .db $d, $1c, $9, $1f
  .db $30, $ec, $6
  .db $d, $1c, $9, $18
  .db $30, $ec, $5
  .db $d, $1c, $9, $1f
  .db $30, $ec, $6
  .db $5, $1a, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $5
  .db $d, $1c, $9, $18
  .db $30, $ec, $5
  .db $d, $1b, $9, $1f
  .db $30, $ec, $6
  .db $5, $1c, $9
  .db $30, $ec, $4
  .db $5, $1a, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $30, $ec, $5
  .db $5, $21, $9
  .db $30, $ec, $6
  .db $5, $23, $9
  .db $30, $ec, $5
  .db $5, $21, $9
  .db $30, $ec, $6
  .db $5, $1f, $9
  .db $30, $ec, $5
  .db $5, $1c, $9
  .db $e2
  .db $30, $ec, $4
  .db $5, $23, $9
  .db $30, $ec, $6
  .db $5, $21, $9
  .db $30, $ec, $5
  .db $5, $1f, $9
  .db $30, $ec, $6
  .db $5, $1c, $9
  .db $30, $ec, $5
  .db $5, $1a, $9
  .db $30, $ec, $5
  .db $5, $17, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $17, $9
  .db $30, $ec, $4
  .db $5, $1a, $9
  .db $e5


;......................................
.pattern.table.chan2.pattern4

  .db $31, $e0, $8, $ef
  .db $f9
  .db $3d, $26, $a, $1e, $10, $7
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $2b, $b
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e4
  .db $30, $ec, $6
  .db $5, $26, $a
  .db $30, $ec, $4
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2a, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $2e, $a
  .db $30, $ec, $4
  .db $5, $2d, $a
  .db $30, $ec, $6
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $32, $a
  .db $e1


;......................................
.pattern.table.chan2.pattern5

  .db $e7
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $4
  .db $5, $2a, $a
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2a, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $30, $ec, $4
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2e, $a
  .db $e2
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $e4
  .db $30, $ec, $6
  .db $5, $26, $a
  .db $30, $ec, $4
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2a, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $2e, $a
  .db $30, $ec, $4
  .db $5, $2d, $a
  .db $30, $ec, $6
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $32, $a
  .db $e1


;......................................
.pattern.table.chan2.pattern6

  .db $e2
  .db $30, $4, $64
  .db $e9
  .db $31, $e0, $4, $0
  .db $ed
  .db $3d, $26, $a, $1e, $10, $7
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $2b, $b
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e4
  .db $30, $ec, $6
  .db $5, $26, $a
  .db $30, $ec, $4
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2a, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $2e, $a
  .db $30, $ec, $4
  .db $5, $2d, $a
  .db $30, $ec, $6
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $32, $a
  .db $e1


;......................................
.pattern.table.chan2.pattern7

  .db $e7
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $4
  .db $5, $2a, $a
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2a, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $30, $ec, $4
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2e, $a
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $e4
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e3
  .db $30, $4, $64
  .db $ed


;......................................
.pattern.table.chan2.pattern8

  .db $e7
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $4
  .db $5, $2a, $a
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2a, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $30, $ec, $4
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2e, $a
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $e4
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e3
  .db $30, $4, $64
  .db $e9
  .db $7d, $13, $9, $1f, $10, $6, $3, $8, $fe
  .db $e3


;......................................
.pattern.table.chan2.pattern9

  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $6
  .db $5, $13, $9
  .db $30, $ec, $4
  .db $5, $10, $9
  .db $30, $ec, $6
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $5
  .db $5, $17, $9
  .db $30, $ec, $6
  .db $5, $16, $9
  .db $30, $ec, $4
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $5
  .db $5, $e, $9
  .db $30, $ec, $5
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $d, $13, $9, $18
  .db $30, $ec, $5
  .db $d, $15, $9, $1f
  .db $30, $ec, $6
  .db $d, $15, $9, $18
  .db $30, $ec, $4
  .db $d, $17, $9, $1f
  .db $30, $ec, $6
  .db $d, $17, $9, $18
  .db $30, $ec, $5
  .db $d, $13, $9, $1f
  .db $30, $ec, $6
  .db $d, $13, $9, $18
  .db $30, $ec, $5
  .db $d, $17, $9, $1f
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $17, $9
  .db $30, $ec, $6
  .db $5, $15, $9
  .db $30, $ec, $4
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $e, $9
  .db $30, $ec, $5


;......................................
.pattern.table.chan2.pattern10

  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $6
  .db $5, $13, $9
  .db $30, $ec, $4
  .db $5, $10, $9
  .db $30, $ec, $6
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $5
  .db $5, $17, $9
  .db $30, $ec, $6
  .db $5, $16, $9
  .db $30, $ec, $4
  .db $5, $15, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $5
  .db $5, $e, $9
  .db $30, $ec, $5
  .db $5, $10, $9
  .db $30, $ec, $5
  .db $5, $13, $9
  .db $30, $ec, $6
  .db $d, $13, $9, $18
  .db $30, $ec, $5
  .db $d, $15, $9, $1f
  .db $30, $ec, $6
  .db $d, $15, $9, $18
  .db $30, $ec, $4
  .db $d, $17, $9, $1f
  .db $30, $ec, $6
  .db $d, $17, $9, $18
  .db $30, $ec, $5
  .db $d, $1a, $9, $1f
  .db $30, $ec, $6
  .db $d, $1a, $9, $18
  .db $e2
  .db $30, $ec, $5
  .db $d, $17, $6, $1f
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan3.pattern0

  .db $fe
  .db $fe
  .db $e4


;......................................
.pattern.table.chan3.pattern1

  .db $fe
  .db $e2
  .db $7d, $23, $a, $1e, $10, $7, $f, $e5, $88, $8, $ef
  .db $30, $ec, $5
  .db $5, $21, $a
  .db $30, $ec, $6
  .db $5, $1f, $a
  .db $30, $ec, $5
  .db $5, $1c, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $1f, $a
  .db $30, $ec, $6
  .db $5, $21, $a
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $28, $b
  .db $e2
  .db $30, $ec, $4
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e1


;......................................
.pattern.table.chan3.pattern2

  .db $75, $2b, $6, $10, $5, $f, $e5, $80, $8, $ff
  .db $35, $2e, $6, $3, $4
  .db $ea
  .db $5, $2f, $6
  .db $ed
  .db $5, $2b, $6
  .db $e1
  .db $5, $26, $6
  .db $e1
  .db $5, $28, $6
  .db $f5
  .db $5, $2e, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2e, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1


;......................................
.pattern.table.chan3.pattern3

  .db $5, $2d, $6
  .db $35, $2f, $6, $3, $4
  .db $f2
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $32, $6
  .db $eb
  .db $5, $2f, $6
  .db $e1
  .db $5, $32, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2e, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $28, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2e, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $28, $6
  .db $e3


;......................................
.pattern.table.chan3.pattern4

  .db $35, $2b, $6, $10, $5
  .db $eb
  .db $5, $2a, $6
  .db $ef
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e7
  .db $5, $2d, $6
  .db $e7
  .db $5, $2b, $6
  .db $e7
  .db $5, $2a, $6
  .db $e7


;......................................
.pattern.table.chan3.pattern5

  .db $5, $2b, $6
  .db $eb
  .db $5, $2a, $6
  .db $ef
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $28, $6
  .db $e1
  .db $5, $2a, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $28, $6
  .db $e9
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1


;......................................
.pattern.table.chan3.pattern6

  .db $5, $2b, $6
  .db $eb
  .db $5, $2a, $6
  .db $ef
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $28, $6
  .db $e1
  .db $5, $2a, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $28, $6
  .db $e9
  .db $30, $2, $1f
  .db $e7


;......................................
.pattern.table.chan3.pattern7

  .db $7d, $37, $6, $1e, $2, $0, $3, $10, $8
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $e1
  .db $d, $37, $6, $1e
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $5
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $e1
  .db $d, $37, $6, $1e
  .db $30, $ec, $4
  .db $5, $34, $6
  .db $30, $ec, $5
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $f5
  .db $d, $2f, $6, $1e
  .db $30, $ec, $5
  .db $5, $32, $6
  .db $30, $ec, $6
  .db $d, $32, $6, $18
  .db $30, $ec, $5
  .db $d, $33, $6, $1e
  .db $30, $ec, $6


;......................................
.pattern.table.chan3.pattern8

  .db $d, $37, $6, $1e
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $e1
  .db $d, $37, $6, $1e
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $5
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $e1
  .db $d, $37, $6, $1e
  .db $30, $ec, $4
  .db $5, $34, $6
  .db $30, $ec, $5
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $6
  .db $3d, $37, $6, $1e, $2, $0
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $e1
  .db $d, $37, $6, $1e
  .db $30, $ec, $5
  .db $5, $34, $6
  .db $30, $ec, $6
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $5
  .db $d, $34, $6, $18
  .db $e1
  .db $e0
  .db $e1
  .db $d, $37, $6, $1e
  .db $30, $ec, $4
  .db $5, $34, $6
  .db $30, $ec, $5
  .db $d, $34, $6, $18
  .db $30, $ec, $5
  .db $d, $34, $6, $1e
  .db $30, $ec, $6


;......................................
.pattern.table.chan3.pattern9

  .db $31, $e0, $2, $0
  .db $fe
  .db $eb
  .db $7d, $23, $a, $1e, $10, $7, $3, $8, $ef
  .db $e2
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e1


;......................................
.pattern.table.chan3.pattern10

  .db $e8
  .db $e0
  .db $fe
  .db $e3
  .db $7d, $23, $a, $1e, $10, $7, $3, $8, $ef
  .db $e2
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e1


;......................................
.pattern.table.chan3.pattern11

  .db $e8
  .db $e0
  .db $fe
  .db $e3
  .db $7d, $23, $a, $1e, $10, $7, $3, $8, $ef
  .db $e2
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $30, $ec, $6


;......................................
.pattern.table.chan3.pattern12

  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $e2
  .db $30, $ec, $6
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $2f, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $32, $a
  .db $30, $ec, $5
  .db $5, $32, $a
  .db $e2
  .db $30, $ec, $6
  .db $5, $2f, $a
  .db $30, $ec, $4
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $30, $ec, $4
  .db $5, $2f, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2f, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2f, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2f, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $30, $ec, $4
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5


;......................................
.pattern.table.chan3.pattern13

  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $6
  .db $5, $2b, $a
  .db $30, $ec, $4
  .db $5, $28, $a
  .db $30, $ec, $6
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $6
  .db $5, $28, $a
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $2f, $a
  .db $30, $ec, $6
  .db $5, $2e, $a
  .db $30, $ec, $4
  .db $5, $2d, $a
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $28, $b
  .db $30, $ec, $5
  .db $5, $2b, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $2d, $a
  .db $e2
  .db $30, $ec, $4
  .db $5, $2f, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $32, $a
  .db $e4
  .db $30, $ec, $5
  .db $5, $34, $a
  .db $e6
  .db $30, $ec, $6
  .db $d, $34, $a, $18
  .db $e3


;........................................................................
;........................................................................

;......................................
.pattern.table.chan4.pattern0

  .db $31, $e0, $2, $0
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan4.pattern1

  .db $30, $e5, $88
  .db $e3
  .db $3d, $2b, $6, $18, $10, $5
  .db $35, $2e, $6, $3, $4
  .db $ea
  .db $5, $2f, $6
  .db $ed
  .db $5, $2b, $6
  .db $e1
  .db $5, $26, $6
  .db $e1
  .db $5, $28, $6
  .db $e7
  .db $7d, $23, $a, $1e, $10, $7, $3, $8, $ef
  .db $e2
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e1


;......................................
.pattern.table.chan4.pattern2

  .db $e4
  .db $7d, $2d, $6, $18, $10, $5, $3, $8, $ff
  .db $35, $2f, $6, $3, $4
  .db $f2
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $35, $32, $6, $e5, $90
  .db $eb
  .db $35, $2f, $6, $e5, $88
  .db $e1
  .db $7d, $23, $a, $1e, $10, $7, $3, $8, $ef
  .db $e2
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $30, $ec, $5
  .db $5, $23, $a
  .db $30, $ec, $5
  .db $5, $26, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e2
  .db $30, $ec, $5
  .db $5, $28, $a
  .db $e1


;......................................
.pattern.table.chan4.pattern3

  .db $e4
  .db $3d, $2b, $6, $18, $10, $5
  .db $eb
  .db $5, $2a, $6
  .db $ef
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e7
  .db $5, $2d, $6
  .db $e7
  .db $5, $2b, $6
  .db $e7
  .db $5, $2a, $6
  .db $e3


;......................................
.pattern.table.chan4.pattern4

  .db $e4
  .db $5, $2b, $6
  .db $eb
  .db $5, $2a, $6
  .db $ef
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $28, $6
  .db $e1
  .db $5, $2a, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $28, $6
  .db $e9
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1


;......................................
.pattern.table.chan4.pattern5

  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $eb
  .db $5, $2a, $6
  .db $ed
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e9
  .db $5, $2d, $6
  .db $e7
  .db $5, $2b, $6
  .db $e7
  .db $5, $2a, $6
  .db $e3


;......................................
.pattern.table.chan4.pattern6

  .db $e4
  .db $5, $2b, $6
  .db $eb
  .db $5, $2a, $6
  .db $ef
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $28, $6
  .db $e1
  .db $5, $2a, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2f, $6
  .db $e1
  .db $5, $2d, $6
  .db $e1
  .db $5, $2b, $6
  .db $e1
  .db $5, $28, $6
  .db $e9
  .db $30, $2, $1f
  .db $e3


;........................................................................
;........................................................................

;......................................
.pattern.table.chan5.pattern0

  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $7d, $18, $1, $1d, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $3d, $18, $1, $1f, $11, $0
  .db $70, $11, $1, $c, $f, $6
  .db $45, $18, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $e1
  .db $40, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6


;......................................
.pattern.table.chan5.pattern1

  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $7d, $18, $1, $1d, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $3d, $18, $1, $1f, $11, $0
  .db $70, $11, $1, $c, $f, $6
  .db $45, $18, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $e1
  .db $40, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $75, $18, $1, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $75, $18, $1, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $6


;......................................
.pattern.table.chan5.pattern2

  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $3, $8, $ff
  .db $75, $18, $1, $ed, $4, $c, $f, $6
  .db $30, $11, $1
  .db $75, $18, $1, $ed, $2, $f, $11, $0, $f, $7
  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $35, $18, $1, $11, $0
  .db $70, $11, $1, $c, $f, $6
  .db $35, $18, $1, $11, $0
  .db $70, $11, $1, $c, $f, $5
  .db $35, $18, $1, $11, $0
  .db $70, $11, $1, $c, $f, $6
  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6


;......................................
.pattern.table.chan5.pattern3

  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $7d, $18, $1, $1d, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $3d, $18, $1, $1f, $11, $0
  .db $70, $11, $1, $c, $f, $6
  .db $45, $18, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $e1
  .db $40, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $45, $24, $5, $3, $8, $ff
  .db $75, $23, $4, $11, $0, $c, $f, $7
  .db $35, $24, $5, $11, $1
  .db $75, $23, $4, $11, $0, $c, $f, $6
  .db $35, $24, $5, $11, $1
  .db $75, $1c, $4, $11, $0, $c, $f, $7
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $6
  .db $45, $24, $5, $3, $8, $ff
  .db $75, $17, $4, $11, $0, $c, $f, $7


;......................................
.pattern.table.chan5.pattern4

  .db $75, $18, $5, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $45, $24, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $7
  .db $5, $24, $2
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $45, $24, $3, $f, $8, $fb, $9, $1
  .db $70, $ec, $5, $c, $f, $6
  .db $5, $24, $3
  .db $70, $ec, $5, $c, $f, $7
  .db $7d, $18, $1, $1d, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $3d, $18, $1, $1f, $11, $0
  .db $70, $11, $1, $c, $f, $6
  .db $45, $18, $2, $f, $8, $fb, $9, $1
  .db $40, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $7
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $5
  .db $75, $18, $5, $11, $1, $c, $9, $1
  .db $75, $18, $0, $11, $0, $c, $f, $7
  .db $75, $24, $2, $11, $1, $3, $8, $fb
  .db $40, $c, $f, $6
  .db $75, $18, $1, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $6
  .db $75, $18, $5, $11, $1, $f, $8, $fb, $9, $1
  .db $75, $23, $4, $11, $0, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $1c, $4, $11, $0, $c, $f, $7
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $75, $18, $5, $11, $1, $3, $8, $bf
  .db $75, $1c, $4, $11, $0, $c, $f, $7
  .db $75, $18, $5, $11, $1, $3, $8, $ff
  .db $75, $18, $0, $11, $0, $c, $f, $6
  .db $5, $1c, $1
  .db $75, $1c, $1, $ed, $4, $c, $f, $7
  .db $e1
  .db $75, $1c, $1, $ed, $1, $c, $f, $6
  .db $35, $18, $5, $11, $1
  .db $75, $18, $0, $11, $0, $c, $f, $7




