

;###########################################################################
.pattern.table
  .dw .pattern.table.chan0
  .dw .pattern.table.chan1
  .dw .pattern.table.chan2
  .dw .pattern.table.chan3
  .dw .pattern.table.chan4
  .dw .pattern.table.chan5


;.....................................................
.pattern.table.chan0
  .dw .pattern.table.chan0.pattern0
  .dw .pattern.table.chan0.pattern1
  .dw .pattern.table.chan0.pattern2
  .dw .pattern.table.chan0.pattern3
  .dw .pattern.table.chan0.pattern4
  .dw .pattern.table.chan0.pattern5
  .dw .pattern.table.chan0.pattern6
  .dw .pattern.table.chan0.pattern7
  .dw .pattern.table.chan0.pattern8
  .dw .pattern.table.chan0.pattern9
  .dw .pattern.table.chan0.pattern10
  .dw .pattern.table.chan0.pattern11
  .dw .pattern.table.chan0.pattern12
  .dw .pattern.table.chan0.pattern13
  .dw .pattern.table.chan0.pattern14
  .dw .pattern.table.chan0.pattern15
  .dw .pattern.table.chan0.pattern16
  .dw .pattern.table.chan0.pattern17
  .dw .pattern.table.chan0.pattern18
  .dw .pattern.table.chan0.pattern19
  .dw .pattern.table.chan0.pattern20
  .dw .pattern.table.chan0.pattern21
  .dw .pattern.table.chan0.pattern22
  .dw .pattern.table.chan0.pattern23
  .dw .pattern.table.chan0.pattern24
  .dw .pattern.table.chan0.pattern25
  .dw .pattern.table.chan0.pattern26
;.....................................................
.pattern.table.chan1
  .dw .pattern.table.chan1.pattern0
  .dw .pattern.table.chan1.pattern1
  .dw .pattern.table.chan1.pattern2
  .dw .pattern.table.chan1.pattern3
  .dw .pattern.table.chan1.pattern4
  .dw .pattern.table.chan1.pattern5
  .dw .pattern.table.chan1.pattern6
  .dw .pattern.table.chan1.pattern7
  .dw .pattern.table.chan1.pattern8
  .dw .pattern.table.chan1.pattern9
  .dw .pattern.table.chan1.pattern10
  .dw .pattern.table.chan1.pattern11
  .dw .pattern.table.chan1.pattern12
  .dw .pattern.table.chan1.pattern13
  .dw .pattern.table.chan1.pattern14
  .dw .pattern.table.chan1.pattern15
  .dw .pattern.table.chan1.pattern16
  .dw .pattern.table.chan1.pattern17
  .dw .pattern.table.chan1.pattern18
  .dw .pattern.table.chan1.pattern19
  .dw .pattern.table.chan1.pattern20
  .dw .pattern.table.chan1.pattern21
  .dw .pattern.table.chan1.pattern22
;.....................................................
.pattern.table.chan2
  .dw .pattern.table.chan2.pattern0
  .dw .pattern.table.chan2.pattern1
  .dw .pattern.table.chan2.pattern2
  .dw .pattern.table.chan2.pattern3
  .dw .pattern.table.chan2.pattern4
  .dw .pattern.table.chan2.pattern5
  .dw .pattern.table.chan2.pattern6
  .dw .pattern.table.chan2.pattern7
  .dw .pattern.table.chan2.pattern8
  .dw .pattern.table.chan2.pattern9
  .dw .pattern.table.chan2.pattern10
  .dw .pattern.table.chan2.pattern11
  .dw .pattern.table.chan2.pattern12
  .dw .pattern.table.chan2.pattern13
  .dw .pattern.table.chan2.pattern14
  .dw .pattern.table.chan2.pattern15
  .dw .pattern.table.chan2.pattern16
  .dw .pattern.table.chan2.pattern17
  .dw .pattern.table.chan2.pattern18
  .dw .pattern.table.chan2.pattern19
  .dw .pattern.table.chan2.pattern20
  .dw .pattern.table.chan2.pattern21
  .dw .pattern.table.chan2.pattern22
;.....................................................
.pattern.table.chan3
  .dw .pattern.table.chan3.pattern0
  .dw .pattern.table.chan3.pattern1
  .dw .pattern.table.chan3.pattern2
  .dw .pattern.table.chan3.pattern3
  .dw .pattern.table.chan3.pattern4
  .dw .pattern.table.chan3.pattern5
  .dw .pattern.table.chan3.pattern6
  .dw .pattern.table.chan3.pattern7
  .dw .pattern.table.chan3.pattern8
  .dw .pattern.table.chan3.pattern9
  .dw .pattern.table.chan3.pattern10
  .dw .pattern.table.chan3.pattern11
  .dw .pattern.table.chan3.pattern12
  .dw .pattern.table.chan3.pattern13
  .dw .pattern.table.chan3.pattern14
  .dw .pattern.table.chan3.pattern15
  .dw .pattern.table.chan3.pattern16
  .dw .pattern.table.chan3.pattern17
  .dw .pattern.table.chan3.pattern18
  .dw .pattern.table.chan3.pattern19
  .dw .pattern.table.chan3.pattern20
  .dw .pattern.table.chan3.pattern21
  .dw .pattern.table.chan3.pattern22
  .dw .pattern.table.chan3.pattern23
  .dw .pattern.table.chan3.pattern24
  .dw .pattern.table.chan3.pattern25
  .dw .pattern.table.chan3.pattern26
  .dw .pattern.table.chan3.pattern27
  .dw .pattern.table.chan3.pattern28
  .dw .pattern.table.chan3.pattern29
  .dw .pattern.table.chan3.pattern30
  .dw .pattern.table.chan3.pattern31
  .dw .pattern.table.chan3.pattern32
  .dw .pattern.table.chan3.pattern33
  .dw .pattern.table.chan3.pattern34
  .dw .pattern.table.chan3.pattern35
  .dw .pattern.table.chan3.pattern36
  .dw .pattern.table.chan3.pattern37
  .dw .pattern.table.chan3.pattern38
;.....................................................
.pattern.table.chan4
  .dw .pattern.table.chan4.pattern0
  .dw .pattern.table.chan4.pattern1
  .dw .pattern.table.chan4.pattern2
  .dw .pattern.table.chan4.pattern3
  .dw .pattern.table.chan4.pattern4
  .dw .pattern.table.chan4.pattern5
  .dw .pattern.table.chan4.pattern6
  .dw .pattern.table.chan4.pattern7
;.....................................................
.pattern.table.chan5
  .dw .pattern.table.chan5.pattern0
  .dw .pattern.table.chan5.pattern1
  .dw .pattern.table.chan5.pattern2
  .dw .pattern.table.chan5.pattern3
  .dw .pattern.table.chan5.pattern4
  .dw .pattern.table.chan5.pattern5
  .dw .pattern.table.chan5.pattern6
  .dw .pattern.table.chan5.pattern7
  .dw .pattern.table.chan5.pattern8
  .dw .pattern.table.chan5.pattern9
  .dw .pattern.table.chan5.pattern10


;###########################################################################


;........................................................................
;........................................................................

;......................................
.pattern.table.chan0.pattern0

  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $4, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $7, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $7, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern1

  .db $5, $c, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $c, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $13, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $1f, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $17, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern2

  .db $5, $18, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $c, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $13, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $1f, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $17, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern3

  .db $5, $15, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $c, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $e, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $1a, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern4

  .db $5, $17, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $e, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $10, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $1c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $12, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $12, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $15, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern5

  .db $5, $17, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $e7
  .db $5, $17, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $17, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $17, $7
  .db $e3
  .db $e0
  .db $fb


;......................................
.pattern.table.chan0.pattern6

  .db $5, $15, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $c, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $e, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $1a, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern7

  .db $5, $b, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $e, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $10, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $1c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $12, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern8

  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $15, $7
  .db $e3
  .db $35, $17, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $f, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern9

  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $10, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $f, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $e, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $d, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $17, $7
  .db $e3
  .db $35, $19, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $19, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern10

  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e3
  .db $35, $15, $7, $3, $8f
  .db $e2
  .db $30, $ec, $2
  .db $5, $18, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern11

  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e3
  .db $35, $10, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e3
  .db $35, $15, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern12

  .db $5, $b, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $6, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e3
  .db $35, $12, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $e3
  .db $35, $17, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern13

  .db $5, $a, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $a, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $a, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $a, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $5, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $8, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $a, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $f, $7
  .db $e3
  .db $35, $11, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $14, $7
  .db $e3
  .db $35, $16, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $a, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern14

  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e3
  .db $35, $10, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e3
  .db $35, $15, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern15

  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e3
  .db $35, $15, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1a, $7
  .db $e3
  .db $35, $1c, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern16

  .db $5, $e, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $18, $7
  .db $e3
  .db $35, $1a, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $d, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $17, $7
  .db $e3
  .db $35, $19, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern17

  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e3
  .db $35, $15, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $18, $7
  .db $e3
  .db $5, $c, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $c, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern18

  .db $5, $e, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e3
  .db $35, $b, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $15, $7
  .db $e3
  .db $35, $17, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $f, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern19

  .db $5, $10, $7
  .db $fe
  .db $e1
  .db $e0
  .db $e3
  .db $5, $1a, $7
  .db $e3
  .db $35, $1c, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1f, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $1f, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $1f, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $7
  .db $e3
  .db $35, $1a, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern20

  .db $5, $17, $7
  .db $e3
  .db $35, $15, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e3
  .db $35, $e, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e3
  .db $35, $b, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $fe
  .db $e5


;......................................
.pattern.table.chan0.pattern21

  .db $f7
  .db $30, $ec, $2
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e3
  .db $35, $10, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern22

  .db $5, $4, $7
  .db $e6
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $35, $10, $7, $3, $f
  .db $e5
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $e, $7
  .db $35, $10, $7, $3, $f
  .db $e5
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $7, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $7, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $9, $7
  .db $ea
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern23

  .db $5, $4, $7
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan0.pattern24

  .db $e3
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $9, $7
  .db $35, $b, $7, $3, $f
  .db $e5
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $f, $7
  .db $35, $10, $7, $3, $f
  .db $e5
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $30, $ec, $1
  .db $5, $4, $7
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e3
  .db $35, $10, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $12, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern25

  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1


;......................................
.pattern.table.chan0.pattern26

  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $f, $7
  .db $e3
  .db $35, $10, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e1
  .db $e0
  .db $e1
  .db $5, $f, $7
  .db $e3
  .db $35, $10, $7, $3, $4f
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $7
  .db $e3
  .db $e0
  .db $ef
  .db $5, $a, $7
  .db $e1
  .db $5, $b, $7
  .db $e1
  .db $5, $c, $7
  .db $e1
  .db $5, $d, $7
  .db $e1
  .db $5, $e, $7
  .db $e1
  .db $5, $f, $7
  .db $e1


;........................................................................
;........................................................................

;......................................
.pattern.table.chan1.pattern0

  .db $7d, $26, $9, $1b, $10, $6, $3, $8, $fd
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $9
  .db $eb
  .db $5, $26, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e7
  .db $5, $26, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $9
  .db $e7


;......................................
.pattern.table.chan1.pattern1

  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $eb
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e7


;......................................
.pattern.table.chan1.pattern2

  .db $5, $24, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $24, $9
  .db $eb
  .db $5, $24, $9
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $e0
  .db $e7
  .db $5, $24, $9
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $24, $9
  .db $e7


;......................................
.pattern.table.chan1.pattern3

  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $9
  .db $e7
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $fb


;......................................
.pattern.table.chan1.pattern4

  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $ef
  .db $5, $33, $9
  .db $eb


;......................................
.pattern.table.chan1.pattern5

  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $e0
  .db $eb
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern6

  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern7

  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $5, $2d, $9
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2a, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern8

  .db $5, $2c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2c, $9
  .db $e7
  .db $5, $2c, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2c, $9
  .db $e7
  .db $5, $2c, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern9

  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern10

  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern11

  .db $5, $24, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $24, $9
  .db $e7
  .db $5, $24, $9
  .db $e3
  .db $5, $24, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $27, $9
  .db $e7
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3
  .db $5, $27, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern12

  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2a, $9
  .db $e3
  .db $5, $26, $9
  .db $e7
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $26, $9
  .db $e7
  .db $5, $26, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern13

  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $24, $9
  .db $e7
  .db $5, $24, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $24, $9
  .db $e7
  .db $5, $24, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern14

  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern15

  .db $5, $2a, $9
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan1.pattern16

  .db $e0
  .db $e7
  .db $35, $2b, $9, $8, $ff
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $1c, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern17

  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $1a, $9
  .db $e3
  .db $5, $1c, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $1c, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $1c, $9
  .db $e3
  .db $5, $1a, $9
  .db $e3
  .db $5, $17, $9
  .db $e3
  .db $5, $15, $9
  .db $e3
  .db $5, $17, $9
  .db $e3
  .db $5, $13, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern18

  .db $5, $e, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $25, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern19

  .db $5, $1c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $15, $9
  .db $e3
  .db $5, $17, $9
  .db $e3
  .db $5, $1c, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $29, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $26, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern20

  .db $5, $23, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $21, $9
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $1c, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern21

  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $25, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3


;......................................
.pattern.table.chan1.pattern22

  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $fb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan2.pattern0

  .db $e1
  .db $7d, $2a, $9, $1b, $10, $6, $3, $8, $df
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $eb
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e7
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e6


;......................................
.pattern.table.chan2.pattern1

  .db $e1
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $eb
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e6


;......................................
.pattern.table.chan2.pattern2

  .db $e1
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $eb
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e6


;......................................
.pattern.table.chan2.pattern3

  .db $e1
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $fa


;......................................
.pattern.table.chan2.pattern4

  .db $e1
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $ef
  .db $5, $3b, $9
  .db $ea


;......................................
.pattern.table.chan2.pattern5

  .db $e1
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $eb
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern6

  .db $e1
  .db $5, $34, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $34, $9
  .db $e7
  .db $5, $34, $9
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $34, $9
  .db $e7
  .db $5, $34, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern7

  .db $e1
  .db $5, $32, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $32, $9
  .db $e7
  .db $5, $32, $9
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $32, $9
  .db $e7
  .db $5, $32, $9
  .db $e3
  .db $5, $32, $9
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $5, $2d, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern8

  .db $e1
  .db $5, $30, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $5, $30, $9
  .db $e3
  .db $5, $2c, $9
  .db $e7
  .db $5, $2c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $2c, $9
  .db $e7
  .db $5, $2c, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern9

  .db $e1
  .db $5, $30, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $5, $30, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern10

  .db $e1
  .db $5, $34, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $34, $9
  .db $e7
  .db $5, $34, $9
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern11

  .db $e1
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern12

  .db $e1
  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern13

  .db $e1
  .db $5, $2d, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $5, $2d, $9
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2a, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $5, $2a, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern14

  .db $e1
  .db $5, $2c, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2c, $9
  .db $e7
  .db $5, $2c, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2c, $9
  .db $e7
  .db $5, $2c, $9
  .db $e3
  .db $5, $2c, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern15

  .db $e1
  .db $5, $2b, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $5, $28, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern16

  .db $e1
  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $e0
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2b, $9
  .db $e2


;......................................
.pattern.table.chan2.pattern17

  .db $e1
  .db $5, $2d, $9
  .db $fe
  .db $fe
  .db $e2


;......................................
.pattern.table.chan2.pattern18

  .db $7d, $2f, $8, $19, $10, $8, $3, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $f8
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $fe


;......................................
.pattern.table.chan2.pattern19

  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $fe
  .db $fe


;......................................
.pattern.table.chan2.pattern20

  .db $fc
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $fe


;......................................
.pattern.table.chan2.pattern21

  .db $fe
  .db $fe
  .db $e4


;......................................
.pattern.table.chan2.pattern22

  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $e4
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $26, $8
  .db $e3
  .db $35, $25, $8, $3, $8
  .db $e3
  .db $35, $26, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $2c, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2c, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e2


;........................................................................
;........................................................................

;......................................
.pattern.table.chan3.pattern0

  .db $e8
  .db $3d, $23, $8, $1d, $10, $7
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $2b, $8, $1d, $8, $ff
  .db $eb
  .db $5, $2d, $8
  .db $e3
  .db $5, $2f, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $26, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern1

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $23, $8, $1d, $8, $ff
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $2b, $8, $1d, $8, $ff
  .db $eb
  .db $5, $2d, $8
  .db $e3
  .db $5, $2f, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $26, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern2

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $2d, $8, $1d, $8, $ff
  .db $e3
  .db $5, $2f, $8
  .db $e3
  .db $5, $32, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $31, $e0, $8, $ff
  .db $f7


;......................................
.pattern.table.chan3.pattern3

  .db $f4
  .db $d, $1f, $8, $1d
  .db $e7
  .db $30, $4, $63
  .db $e7
  .db $35, $21, $8, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $e7
  .db $35, $23, $8, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $e3


;......................................
.pattern.table.chan3.pattern4

  .db $35, $28, $8, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $e9
  .db $e0
  .db $e3
  .db $35, $26, $8, $4, $0
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3


;......................................
.pattern.table.chan3.pattern5

  .db $3d, $23, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $1f, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $1f, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $1c, $8, $1d, $8, $ff
  .db $e3
  .db $5, $1f, $8
  .db $e7
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $1f, $8, $1d, $8, $ff
  .db $e7
  .db $30, $4, $64
  .db $e7


;......................................
.pattern.table.chan3.pattern6

  .db $fe
  .db $ea
  .db $31, $e0, $4, $0
  .db $e3
  .db $3d, $2f, $8, $1b, $10, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e2
  .db $30, $ec, $2
  .db $3d, $2d, $8, $1b, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern7

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $ee
  .db $30, $ec, $2
  .db $3d, $28, $8, $1b, $8, $ff
  .db $ee
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $ee
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $ea
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern8

  .db $5, $2d, $8
  .db $fe
  .db $e4
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $32, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e2
  .db $30, $ec, $2
  .db $3d, $2a, $8, $1b, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern9

  .db $5, $28, $8
  .db $fe
  .db $e8
  .db $30, $ec, $2
  .db $3d, $1c, $8, $1d, $10, $7
  .db $e3
  .db $5, $1a, $8
  .db $e3
  .db $5, $1c, $8
  .db $e3
  .db $5, $1f, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern10

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $26, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $24, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $23, $8, $1d, $8, $ff
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e5
  .db $35, $17, $8, $3, $f
  .db $ed
  .db $e0
  .db $eb


;......................................
.pattern.table.chan3.pattern11

  .db $5, $2d, $8
  .db $fe
  .db $e4
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $32, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e2
  .db $30, $ec, $2
  .db $3d, $34, $8, $1b, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $32, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $37, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern12

  .db $5, $34, $8
  .db $fe
  .db $e9
  .db $3d, $17, $8, $1d, $10, $7
  .db $e3
  .db $5, $1a, $8
  .db $e3
  .db $5, $1c, $8
  .db $e3
  .db $5, $1f, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern13

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $2b, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $33, $8, $1d, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $33, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $ea
  .db $31, $e0, $8, $ff
  .db $3d, $23, $8, $1d, $10, $9
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $2a, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern14

  .db $5, $2b, $8
  .db $fe
  .db $e5
  .db $e0
  .db $e7
  .db $5, $2d, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2a, $8, $1d, $8, $ff
  .db $e3
  .db $5, $28, $8
  .db $e6
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern15

  .db $35, $28, $8, $8, $ff
  .db $fe
  .db $e5
  .db $5, $26, $8
  .db $fb


;......................................
.pattern.table.chan3.pattern16

  .db $e4
  .db $e0
  .db $e7
  .db $5, $21, $8
  .db $35, $23, $8, $3, $f
  .db $ee
  .db $5, $26, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $28, $8, $1d, $8, $ff
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2b, $8, $1d, $8, $ff
  .db $e7
  .db $5, $28, $8
  .db $e3
  .db $5, $26, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern17

  .db $5, $28, $8
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan3.pattern18

  .db $5, $2d, $8
  .db $e1
  .db $35, $2f, $8, $3, $2
  .db $fe
  .db $eb
  .db $5, $32, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e3
  .db $5, $2d, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern19

  .db $5, $2d, $8
  .db $e7
  .db $5, $26, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $26, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $23, $8, $1d, $8, $ff
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $2a, $8
  .db $e3
  .db $35, $28, $8, $3, $1f
  .db $e3
  .db $38, $14, $8, $df
  .db $e1
  .db $e0
  .db $e1
  .db $3d, $26, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $28, $8, $1d, $8, $ff
  .db $e3
  .db $5, $2a, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern20

  .db $5, $2b, $8
  .db $e7
  .db $5, $28, $8
  .db $e3
  .db $5, $2a, $8
  .db $e3
  .db $5, $2b, $8
  .db $e7
  .db $5, $28, $8
  .db $e3
  .db $5, $2a, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2d, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3


;......................................
.pattern.table.chan3.pattern21

  .db $3d, $32, $8, $1d, $8, $ff
  .db $35, $34, $8, $3, $2
  .db $ee
  .db $5, $30, $8
  .db $35, $32, $8, $3, $2
  .db $ea
  .db $5, $30, $8
  .db $e3
  .db $3d, $30, $8, $14, $8, $df
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e1
  .db $e0
  .db $e1
  .db $5, $2e, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2e, $8
  .db $e1
  .db $e0
  .db $e1
  .db $5, $2d, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $5, $2a, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern22

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e7
  .db $3d, $28, $8, $1d, $8, $ff
  .db $e7
  .db $5, $26, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2b, $8, $1d, $8, $ff
  .db $e7
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2d, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2a, $8, $1d, $8, $ff
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3


;......................................
.pattern.table.chan3.pattern23

  .db $3d, $28, $8, $1d, $8, $ff
  .db $f7
  .db $38, $14, $8, $df
  .db $e1
  .db $e0
  .db $e1
  .db $3d, $2a, $8, $1d, $8, $ff
  .db $e3
  .db $35, $28, $8, $3, $1f
  .db $e3
  .db $5, $26, $8
  .db $fb


;......................................
.pattern.table.chan3.pattern24

  .db $e0
  .db $e3
  .db $3d, $26, $8, $14, $8, $df
  .db $e7
  .db $3d, $23, $8, $1d, $8, $ff
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $2b, $8
  .db $e7
  .db $5, $28, $8
  .db $e3
  .db $5, $26, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern25

  .db $5, $28, $8
  .db $fe
  .db $e1
  .db $e0
  .db $eb
  .db $5, $2b, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e7
  .db $3d, $2d, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3


;......................................
.pattern.table.chan3.pattern26

  .db $3d, $2d, $8, $1d, $8, $ff
  .db $e3
  .db $35, $2f, $8, $3, $2
  .db $fe
  .db $e5
  .db $38, $14, $8, $df
  .db $e1
  .db $e0
  .db $e1
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e3
  .db $5, $2d, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern27

  .db $5, $2d, $8
  .db $e7
  .db $5, $2f, $8
  .db $e3
  .db $5, $32, $8
  .db $e3
  .db $5, $2f, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $34, $8, $1d, $8, $ff
  .db $e3
  .db $5, $36, $8
  .db $e3
  .db $35, $34, $8, $3, $4
  .db $e5
  .db $38, $14, $8, $df
  .db $e1
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $34, $8, $1d, $8, $ff
  .db $e3
  .db $5, $36, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern28

  .db $5, $37, $8
  .db $e7
  .db $5, $34, $8
  .db $e3
  .db $5, $36, $8
  .db $e3
  .db $5, $37, $8
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $8
  .db $e3
  .db $5, $2a, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2d, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3
  .db $3d, $32, $8, $1d, $8, $ff
  .db $e3
  .db $38, $14, $8, $df
  .db $e3


;......................................
.pattern.table.chan3.pattern29

  .db $3d, $32, $8, $1d, $8, $ff
  .db $35, $34, $8, $3, $2
  .db $ee
  .db $5, $32, $8
  .db $35, $34, $8, $3, $2
  .db $ea
  .db $5, $32, $8
  .db $e3
  .db $3d, $32, $8, $14, $8, $df
  .db $e3
  .db $3d, $2f, $8, $1d, $8, $ff
  .db $e3
  .db $5, $32, $8
  .db $e3
  .db $5, $34, $8
  .db $e3
  .db $5, $32, $8
  .db $e3
  .db $5, $37, $8
  .db $e3
  .db $5, $34, $8
  .db $e3
  .db $5, $32, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern30

  .db $5, $34, $8
  .db $e7
  .db $3d, $2a, $8, $1b, $10, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2a, $8
  .db $e3
  .db $35, $29, $8, $3, $8
  .db $e3
  .db $35, $2a, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $31, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $31, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $e2


;......................................
.pattern.table.chan3.pattern31

  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $25, $8
  .db $e3
  .db $35, $26, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $25, $8
  .db $e3
  .db $35, $26, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $21, $8
  .db $e3
  .db $35, $23, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1f, $8
  .db $e3
  .db $35, $21, $8, $3, $1f
  .db $e3
  .db $35, $1f, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern32

  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $26, $8
  .db $e3
  .db $35, $28, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $8
  .db $e3
  .db $35, $2b, $8, $3, $f
  .db $e3
  .db $5, $28, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $28, $8
  .db $e3
  .db $35, $26, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $23, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $21, $8
  .db $e3
  .db $35, $23, $8, $3, $1f
  .db $e3
  .db $5, $1f, $8
  .db $e3


;......................................
.pattern.table.chan3.pattern33

  .db $5, $1a, $8
  .db $e3
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $2b, $8
  .db $e3
  .db $35, $2c, $8, $3, $f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $32, $8
  .db $e3
  .db $35, $33, $8, $3, $f
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $21, $8
  .db $e3
  .db $35, $23, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $1f, $8
  .db $e3
  .db $35, $21, $8, $3, $1f
  .db $e3
  .db $35, $1f, $8, $3, $1f
  .db $e3


;......................................
.pattern.table.chan3.pattern34

  .db $5, $1c, $8
  .db $e3
  .db $e0
  .db $e3
  .db $5, $15, $8
  .db $e3
  .db $35, $17, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1f, $8
  .db $e3
  .db $35, $21, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $23, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e0
  .db $e2
  .db $5, $2d, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2e, $8
  .db $e3
  .db $35, $2d, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern35

  .db $5, $28, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $25, $8
  .db $e3
  .db $35, $26, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $25, $8
  .db $e3
  .db $35, $26, $8, $3, $1f
  .db $e3
  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $21, $8
  .db $e3
  .db $35, $23, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1f, $8
  .db $e3
  .db $35, $21, $8, $3, $1f
  .db $e3
  .db $35, $1f, $8, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern36

  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $35, $2a, $8, $10, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2a, $8
  .db $e3
  .db $35, $29, $8, $3, $8
  .db $e3
  .db $35, $2a, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $31, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $31, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2f, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $30, $ec, $1
  .db $e2


;......................................
.pattern.table.chan3.pattern37

  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $25, $8
  .db $e3
  .db $35, $26, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $8
  .db $e0
  .db $e2
  .db $5, $25, $8
  .db $e3
  .db $35, $26, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $8
  .db $30, $ec, $1
  .db $f2
  .db $3d, $22, $8, $1d, $10, $7
  .db $e1
  .db $5, $23, $8
  .db $e1
  .db $5, $24, $8
  .db $e1
  .db $5, $25, $8
  .db $e1
  .db $5, $26, $8
  .db $e1
  .db $5, $27, $8
  .db $e1


;......................................
.pattern.table.chan3.pattern38

  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $23, $8, $1d, $8, $ff
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $38, $14, $8, $fd
  .db $e3
  .db $3d, $2b, $8, $1d, $8, $ff
  .db $eb
  .db $5, $2d, $8
  .db $e3
  .db $5, $2f, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $26, $8
  .db $e2
  .db $30, $b, $1


;........................................................................
;........................................................................

;......................................
.pattern.table.chan4.pattern0

  .db $fe
  .db $fe
  .db $e4


;......................................
.pattern.table.chan4.pattern1

  .db $fe
  .db $ee
  .db $3d, $2b, $8, $19, $10, $8
  .db $e3
  .db $38, $12, $8, $fd
  .db $e2
  .db $30, $ec, $2
  .db $3d, $2a, $8, $19, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $28, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan4.pattern2

  .db $5, $24, $8
  .db $e3
  .db $38, $12, $8, $fd
  .db $ee
  .db $30, $ec, $2
  .db $3d, $24, $8, $19, $8, $ff
  .db $ee
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $ee
  .db $30, $ec, $2
  .db $5, $28, $8
  .db $ea
  .db $30, $ec, $2


;......................................
.pattern.table.chan4.pattern3

  .db $5, $2a, $8
  .db $fe
  .db $e4
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $8
  .db $e3
  .db $38, $12, $8, $fd
  .db $e3
  .db $3d, $26, $8, $19, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $28, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $21, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan4.pattern4

  .db $5, $23, $8
  .db $fe
  .db $e9
  .db $e0
  .db $f7


;......................................
.pattern.table.chan4.pattern5

  .db $5, $2a, $8
  .db $fe
  .db $e4
  .db $30, $ec, $2
  .db $5, $2b, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $8
  .db $e3
  .db $38, $12, $8, $fd
  .db $e3
  .db $3d, $2f, $8, $19, $8, $ff
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $32, $8
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan4.pattern6

  .db $5, $2f, $8
  .db $fe
  .db $e9
  .db $e0
  .db $f7


;......................................
.pattern.table.chan4.pattern7

  .db $e8
  .db $d, $26, $8, $19
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $26, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $26, $8
  .db $e3
  .db $35, $25, $8, $3, $8
  .db $e3
  .db $35, $26, $8, $3, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $2c, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2c, $8
  .db $30, $ec, $1
  .db $e2
  .db $5, $2a, $8
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e1
  .db $30, $ec, $2
  .db $5, $2a, $8
  .db $30, $ec, $1
  .db $e2


;........................................................................
;........................................................................

;......................................
.pattern.table.chan5.pattern0

  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3


;......................................
.pattern.table.chan5.pattern1

  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $c, $0, $3, $8, $df
  .db $75, $24, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e4
  .db $35, $c, $0, $11, $1
  .db $75, $24, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e4
  .db $35, $c, $0, $11, $1
  .db $75, $24, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e4
  .db $45, $24, $2, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $24, $3
  .db $e3


;......................................
.pattern.table.chan5.pattern2

  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $35, $28, $5, $11, $0
  .db $35, $30, $0, $11, $1
  .db $35, $28, $5, $11, $0
  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $35, $30, $0, $11, $1
  .db $35, $23, $5, $11, $0
  .db $e2


;......................................
.pattern.table.chan5.pattern3

  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $35, $24, $0, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $75, $24, $0, $11, $1, $3, $8, $df
  .db $75, $28, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $75, $28, $5, $ed, $1, $c, $f, $3
  .db $e1
  .db $35, $28, $5, $ed, $2
  .db $e2
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $23, $5, $11, $0
  .db $e2


;......................................
.pattern.table.chan5.pattern4

  .db $3d, $24, $0, $1f, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $0, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $2, $1b, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e4


;......................................
.pattern.table.chan5.pattern5

  .db $3d, $24, $0, $1f, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $0, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3


;......................................
.pattern.table.chan5.pattern6

  .db $3d, $24, $0, $1f, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $fd
  .db $75, $1b, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $2, $1b, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e4


;......................................
.pattern.table.chan5.pattern7

  .db $3d, $24, $0, $1f, $11, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $2, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $e1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $24, $0
  .db $35, $24, $1, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $45, $24, $0, $3, $8, $ff
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $0, $11, $1, $3, $8, $df
  .db $35, $28, $5, $11, $0
  .db $35, $24, $0, $11, $1
  .db $35, $28, $5, $11, $0
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $23, $5, $11, $0
  .db $e2


;......................................
.pattern.table.chan5.pattern8

  .db $7d, $15, $8, $1b, $10, $2, $3, $8, $ff
  .db $7d, $28, $a, $1f, $11, $1, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $3, $3, $8, $fd
  .db $e3
  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3


;......................................
.pattern.table.chan5.pattern9

  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $18, $6, $3, $8, $df
  .db $30, $11, $0
  .db $e3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $18, $3, $11, $1, $3, $8, $fd
  .db $e3


;......................................
.pattern.table.chan5.pattern10

  .db $5, $18, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $24, $0, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $75, $24, $0, $11, $1, $3, $8, $df
  .db $75, $28, $5, $11, $0, $c, $f, $2
  .db $35, $24, $0, $11, $1
  .db $75, $28, $5, $11, $0, $c, $f, $3
  .db $35, $24, $0, $11, $1
  .db $35, $28, $5, $11, $0
  .db $e2
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $0, $11, $1, $3, $8, $bf
  .db $35, $2d, $5, $11, $0
  .db $e2
  .db $75, $24, $0, $11, $1, $3, $8, $fd
  .db $75, $20, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $35, $23, $5, $11, $0
  .db $e2
  .db $35, $24, $0, $11, $1
  .db $75, $23, $5, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $1
  .db $e1
  .db $5, $c, $1
  .db $e1
  .db $5, $c, $1
  .db $40, $c, $f, $2
  .db $5, $c, $1
  .db $40, $c, $f, $3
  .db $5, $c, $1
  .db $e1
  .db $5, $c, $1
  .db $e1




