
.data.chan1


;..........................
; frame 0

  .db $5f                                       ; 804 -> $5f
  .db $1f                                       ; 804 -> $1f
  .db $b0, $0                                   ; Waveform update #$0
  .db $a5, $ff                                  ; 805 -> $ff
  .db $ff                                       ; Wait vblank

;..........................
; frame 1

  .db $ff                                       ; Wait vblank

;..........................
; frame 2

  .db $ff                                       ; Wait vblank

;..........................
; frame 3

  .db $ff                                       ; Wait vblank

;..........................
; frame 4

  .db $ff                                       ; Wait vblank

;..........................
; frame 5

  .db $ff                                       ; Wait vblank

;..........................
; frame 6

  .db $ff                                       ; Wait vblank

;..........................
; frame 7

  .db $ff                                       ; Wait vblank

;..........................
; frame 8

  .db $ff                                       ; Wait vblank

;..........................
; frame 9

  .db $ff                                       ; Wait vblank

;..........................
; frame 10

  .db $ff                                       ; Wait vblank

;..........................
; frame 11

  .db $ff                                       ; Wait vblank

;..........................
; frame 12

  .db $ff                                       ; Wait vblank

;..........................
; frame 13

  .db $ff                                       ; Wait vblank

;..........................
; frame 14

  .db $ff                                       ; Wait vblank

;..........................
; frame 15

  .db $ff                                       ; Wait vblank

;..........................
; frame 16

  .db $ff                                       ; Wait vblank

;..........................
; frame 17

  .db $ff                                       ; Wait vblank

;..........................
; frame 18

  .db $ff                                       ; Wait vblank

;..........................
; frame 19

  .db $ff                                       ; Wait vblank

;..........................
; frame 20

  .db $ff                                       ; Wait vblank

;..........................
; frame 21

  .db $ff                                       ; Wait vblank

;..........................
; frame 22

  .db $ff                                       ; Wait vblank

;..........................
; frame 23

  .db $ff                                       ; Wait vblank

;..........................
; frame 24

  .db $ff                                       ; Wait vblank

;..........................
; frame 25

  .db $ff                                       ; Wait vblank

;..........................
; frame 26

  .db $ff                                       ; Wait vblank

;..........................
; frame 27

  .db $ff                                       ; Wait vblank

;..........................
; frame 28

  .db $ff                                       ; Wait vblank

;..........................
; frame 29

  .db $ff                                       ; Wait vblank

;..........................
; frame 30

  .db $ff                                       ; Wait vblank

;..........................
; frame 31

  .db $ff                                       ; Wait vblank

;..........................
; frame 32

  .db $ff                                       ; Wait vblank

;..........................
; frame 33

  .db $ff                                       ; Wait vblank

;..........................
; frame 34

  .db $ff                                       ; Wait vblank

;..........................
; frame 35

  .db $ff                                       ; Wait vblank

;..........................
; frame 36

  .db $ff                                       ; Wait vblank

;..........................
; frame 37

  .db $ff                                       ; Wait vblank

;..........................
; frame 38

  .db $ff                                       ; Wait vblank

;..........................
; frame 39

  .db $ff                                       ; Wait vblank

;..........................
; frame 40

  .db $ff                                       ; Wait vblank

;..........................
; frame 41

  .db $ff                                       ; Wait vblank

;..........................
; frame 42

  .db $ff                                       ; Wait vblank

;..........................
; frame 43

  .db $ff                                       ; Wait vblank

;..........................
; frame 44

  .db $ff                                       ; Wait vblank

;..........................
; frame 45

  .db $ff                                       ; Wait vblank

;..........................
; frame 46

  .db $ff                                       ; Wait vblank

;..........................
; frame 47

  .db $ff                                       ; Wait vblank

;..........................
; frame 48

  .db $ff                                       ; Wait vblank

;..........................
; frame 49

  .db $ff                                       ; Wait vblank

;..........................
; frame 50

  .db $ff                                       ; Wait vblank

;..........................
; frame 51

  .db $ff                                       ; Wait vblank

;..........................
; frame 52

  .db $ff                                       ; Wait vblank

;..........................
; frame 53

  .db $ff                                       ; Wait vblank

;..........................
; frame 54

  .db $ff                                       ; Wait vblank

;..........................
; frame 55

  .db $ff                                       ; Wait vblank

;..........................
; frame 56

  .db $ff                                       ; Wait vblank

;..........................
; frame 57

  .db $ff                                       ; Wait vblank

;..........................
; frame 58

  .db $ff                                       ; Wait vblank

;..........................
; frame 59

  .db $ff                                       ; Wait vblank

;..........................
; frame 60

  .db $ff                                       ; Wait vblank

;..........................
; frame 61

  .db $ff                                       ; Wait vblank

;..........................
; frame 62

  .db $ff                                       ; Wait vblank

;..........................
; frame 63

  .db $ff                                       ; Wait vblank

;..........................
; frame 64

  .db $ff                                       ; Wait vblank

;..........................
; frame 65

  .db $fb                                       ; End of channel stream