
.data.chan5


;..........................
; frame 0

  .db $0                                        ; 804 -> $0
  .db $a5, $ff                                  ; 805 -> $ff
  .db $ff                                       ; Wait vblank

;..........................
; frame 1

  .db $ff                                       ; Wait vblank

;..........................
; frame 2

  .db $ff                                       ; Wait vblank

;..........................
; frame 3

  .db $ff                                       ; Wait vblank

;..........................
; frame 4

  .db $ff                                       ; Wait vblank

;..........................
; frame 5

  .db $ff                                       ; Wait vblank

;..........................
; frame 6

  .db $ff                                       ; Wait vblank

;..........................
; frame 7

  .db $ff                                       ; Wait vblank

;..........................
; frame 8

  .db $ff                                       ; Wait vblank

;..........................
; frame 9

  .db $ff                                       ; Wait vblank

;..........................
; frame 10

  .db $ff                                       ; Wait vblank

;..........................
; frame 11

  .db $ff                                       ; Wait vblank

;..........................
; frame 12

  .db $ff                                       ; Wait vblank

;..........................
; frame 13

  .db $ff                                       ; Wait vblank

;..........................
; frame 14

  .db $ff                                       ; Wait vblank

;..........................
; frame 15

  .db $ff                                       ; Wait vblank

;..........................
; frame 16

  .db $ff                                       ; Wait vblank

;..........................
; frame 17

  .db $ff                                       ; Wait vblank

;..........................
; frame 18

  .db $ff                                       ; Wait vblank

;..........................
; frame 19

  .db $ff                                       ; Wait vblank

;..........................
; frame 20

  .db $ff                                       ; Wait vblank

;..........................
; frame 21

  .db $ff                                       ; Wait vblank

;..........................
; frame 22

  .db $ff                                       ; Wait vblank

;..........................
; frame 23

  .db $ff                                       ; Wait vblank

;..........................
; frame 24

  .db $ff                                       ; Wait vblank

;..........................
; frame 25

  .db $ff                                       ; Wait vblank

;..........................
; frame 26

  .db $ff                                       ; Wait vblank

;..........................
; frame 27

  .db $ff                                       ; Wait vblank

;..........................
; frame 28

  .db $fb                                       ; End of channel stream