
; Txx
in_DMA = $D3
ia_DMA = $E3
ii_DMA = $73
dd_DMA = $C3
ai_DMA = $F3

; MPR slots
MPR0 = 0
MPR1 = 1
MPR2 = 2
MPR3 = 3
MPR4 = 4
MPR5 = 5
MPR6 = 6
MPR7 = 7

PAGE_0000 = MPR0
PAGE_2000 = MPR1
PAGE_4000 = MPR2
PAGE_6000 = MPR3
PAGE_8000 = MPR4
PAGE_A000 = MPR5
PAGE_C000 = MPR6
PAGE_E000 = MPR7

AX = $ffff0001
AY = $ffff0002
XY = $ffff0003
AXY = $ffff0004
ACC = $ffff0005
IX = $ffff0006
IY = $ffff0007
Acc = ACC
