

;###########################################################################
.pattern.table
  .dw .pattern.table.chan0
  .dw .pattern.table.chan1
  .dw .pattern.table.chan2
  .dw .pattern.table.chan3
  .dw .pattern.table.chan4
  .dw .pattern.table.chan5


;.....................................................
.pattern.table.chan0
  .dw .pattern.table.chan0.pattern0
  .dw .pattern.table.chan0.pattern1
  .dw .pattern.table.chan0.pattern2
  .dw .pattern.table.chan0.pattern3
  .dw .pattern.table.chan0.pattern4
  .dw .pattern.table.chan0.pattern5
  .dw .pattern.table.chan0.pattern6
  .dw .pattern.table.chan0.pattern7
  .dw .pattern.table.chan0.pattern8
  .dw .pattern.table.chan0.pattern9
;.....................................................
.pattern.table.chan1
  .dw .pattern.table.chan1.pattern0
  .dw .pattern.table.chan1.pattern1
  .dw .pattern.table.chan1.pattern2
  .dw .pattern.table.chan1.pattern3
  .dw .pattern.table.chan1.pattern4
  .dw .pattern.table.chan1.pattern5
  .dw .pattern.table.chan1.pattern6
  .dw .pattern.table.chan1.pattern7
  .dw .pattern.table.chan1.pattern8
  .dw .pattern.table.chan1.pattern9
  .dw .pattern.table.chan1.pattern10
;.....................................................
.pattern.table.chan2
  .dw .pattern.table.chan2.pattern0
  .dw .pattern.table.chan2.pattern1
  .dw .pattern.table.chan2.pattern2
  .dw .pattern.table.chan2.pattern3
  .dw .pattern.table.chan2.pattern4
  .dw .pattern.table.chan2.pattern5
  .dw .pattern.table.chan2.pattern6
  .dw .pattern.table.chan2.pattern7
  .dw .pattern.table.chan2.pattern8
  .dw .pattern.table.chan2.pattern9
;.....................................................
.pattern.table.chan3
  .dw .pattern.table.chan3.pattern0
  .dw .pattern.table.chan3.pattern1
  .dw .pattern.table.chan3.pattern2
  .dw .pattern.table.chan3.pattern3
  .dw .pattern.table.chan3.pattern4
  .dw .pattern.table.chan3.pattern5
  .dw .pattern.table.chan3.pattern6
  .dw .pattern.table.chan3.pattern7
  .dw .pattern.table.chan3.pattern8
  .dw .pattern.table.chan3.pattern9
  .dw .pattern.table.chan3.pattern10
  .dw .pattern.table.chan3.pattern11
  .dw .pattern.table.chan3.pattern12
  .dw .pattern.table.chan3.pattern13
  .dw .pattern.table.chan3.pattern14
  .dw .pattern.table.chan3.pattern15
  .dw .pattern.table.chan3.pattern16
  .dw .pattern.table.chan3.pattern17
  .dw .pattern.table.chan3.pattern18
  .dw .pattern.table.chan3.pattern19
  .dw .pattern.table.chan3.pattern20
  .dw .pattern.table.chan3.pattern21
  .dw .pattern.table.chan3.pattern22
  .dw .pattern.table.chan3.pattern23
  .dw .pattern.table.chan3.pattern24
  .dw .pattern.table.chan3.pattern25
  .dw .pattern.table.chan3.pattern26
  .dw .pattern.table.chan3.pattern27
  .dw .pattern.table.chan3.pattern28
  .dw .pattern.table.chan3.pattern29
  .dw .pattern.table.chan3.pattern30
  .dw .pattern.table.chan3.pattern31
  .dw .pattern.table.chan3.pattern32
  .dw .pattern.table.chan3.pattern33
;.....................................................
.pattern.table.chan4
  .dw .pattern.table.chan4.pattern0
  .dw .pattern.table.chan4.pattern1
  .dw .pattern.table.chan4.pattern2
  .dw .pattern.table.chan4.pattern3
  .dw .pattern.table.chan4.pattern4
  .dw .pattern.table.chan4.pattern5
;.....................................................
.pattern.table.chan5
  .dw .pattern.table.chan5.pattern0
  .dw .pattern.table.chan5.pattern1
  .dw .pattern.table.chan5.pattern2
  .dw .pattern.table.chan5.pattern3
  .dw .pattern.table.chan5.pattern4
  .dw .pattern.table.chan5.pattern5
  .dw .pattern.table.chan5.pattern6
  .dw .pattern.table.chan5.pattern7


;###########################################################################


;........................................................................
;........................................................................

;......................................
.pattern.table.chan0.pattern0

  .db $d, $10, $6, $1f
  .db $e3
  .db $8, $14
  .db $eb
  .db $d, $e, $6, $1f
  .db $e3
  .db $5, $10, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $13, $6, $1f
  .db $e5
  .db $8, $1b
  .db $e5
  .db $8, $1a
  .db $e3
  .db $8, $19
  .db $e3
  .db $8, $18
  .db $e1
  .db $8, $17
  .db $e1
  .db $8, $16
  .db $e1
  .db $8, $15
  .db $e1
  .db $8, $14
  .db $e1
  .db $8, $13
  .db $e1
  .db $8, $12
  .db $e1
  .db $8, $11
  .db $e1


;......................................
.pattern.table.chan0.pattern1

  .db $d, $10, $6, $1f
  .db $e3
  .db $8, $14
  .db $eb
  .db $d, $e, $6, $1f
  .db $e3
  .db $5, $10, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $9, $6, $1f
  .db $e5
  .db $8, $1b
  .db $e5
  .db $8, $1a
  .db $e3
  .db $8, $19
  .db $e3
  .db $8, $18
  .db $e1
  .db $8, $17
  .db $e1
  .db $8, $16
  .db $e1
  .db $8, $15
  .db $e1
  .db $8, $14
  .db $e1
  .db $8, $13
  .db $e1
  .db $8, $12
  .db $e1
  .db $8, $11
  .db $e1


;......................................
.pattern.table.chan0.pattern2

  .db $d, $10, $6, $1f
  .db $e3
  .db $8, $14
  .db $eb
  .db $d, $e, $6, $1f
  .db $e3
  .db $5, $10, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $9, $6, $1f
  .db $e7
  .db $5, $9, $6
  .db $e3
  .db $5, $15, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $6
  .db $e2
  .db $30, $ec, $2
  .db $f0


;......................................
.pattern.table.chan0.pattern3

  .db $5, $b, $6
  .db $e6
  .db $e0
  .db $5, $17, $6
  .db $e6
  .db $e0
  .db $5, $e, $6
  .db $e6
  .db $e0
  .db $5, $1a, $6
  .db $e6
  .db $e0
  .db $fe
  .db $e2


;......................................
.pattern.table.chan0.pattern4

  .db $5, $10, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $9, $6, $1f
  .db $e3
  .db $35, $b, $6, $3, $8f
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $6
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $e, $6, $1f
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $1a, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $6
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern5

  .db $5, $9, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $6
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $15, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $6
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $9, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $6
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $d, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $d, $6
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $e, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $6
  .db $e1
  .db $8, $14
  .db $30, $ec, $2
  .db $d, $10, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $6
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern6

  .db $5, $4, $6
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e2
  .db $30, $ec, $2
  .db $d, $5, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e7
  .db $8, $18
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern7

  .db $d, $6, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e2
  .db $30, $ec, $2
  .db $d, $5, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e7
  .db $8, $18
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern8

  .db $d, $10, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e2
  .db $30, $ec, $2
  .db $d, $11, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e7
  .db $8, $18
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern9

  .db $d, $12, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e2
  .db $30, $ec, $2
  .db $d, $13, $6, $1f
  .db $e7
  .db $8, $1b
  .db $e2
  .db $30, $ec, $2
  .db $d, $17, $6, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $6
  .db $e2
  .db $30, $ec, $2
  .db $f0


;........................................................................
;........................................................................

;......................................
.pattern.table.chan1.pattern0

  .db $3d, $1c, $7, $1f, $10, $7
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan1.pattern1

  .db $35, $15, $7, $10, $8
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan1.pattern2

  .db $35, $1c, $7, $10, $9
  .db $fe
  .db $f1
  .db $3d, $32, $7, $1b, $10, $4
  .db $ef


;......................................
.pattern.table.chan1.pattern3

  .db $5, $34, $7
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan1.pattern4

  .db $e0
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan1.pattern5

  .db $e0
  .db $e3
  .db $7d, $1f, $8, $1d, $10, $4, $3, $8, $fd
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $e0
  .db $e3
  .db $5, $1f, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $d, $23, $8, $1b
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $d, $1f, $8, $1d
  .db $e3
  .db $5, $1e, $8
  .db $e3
  .db $5, $1f, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $23, $8
  .db $e3


;......................................
.pattern.table.chan1.pattern6

  .db $e0
  .db $e3
  .db $5, $1c, $8
  .db $e3
  .db $5, $1a, $8
  .db $e3
  .db $5, $1c, $8
  .db $e3
  .db $5, $1f, $8
  .db $e3
  .db $5, $1c, $8
  .db $e3
  .db $5, $1a, $8
  .db $e3
  .db $5, $19, $8
  .db $e7
  .db $5, $1c, $8
  .db $e7
  .db $5, $1e, $8
  .db $e7
  .db $5, $1f, $8
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $26, $8
  .db $e3


;......................................
.pattern.table.chan1.pattern7

  .db $d, $23, $5, $1b
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $d, $23, $8, $1d
  .db $e3
  .db $5, $23, $b
  .db $e3
  .db $5, $23, $b
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $23, $b
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $b
  .db $e3


;......................................
.pattern.table.chan1.pattern8

  .db $d, $25, $5, $1b
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $d, $25, $8, $1d
  .db $e3
  .db $5, $25, $b
  .db $e3
  .db $5, $25, $b
  .db $e3
  .db $5, $25, $8
  .db $e3
  .db $5, $25, $b
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $8
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $b
  .db $e3
  .db $5, $24, $b
  .db $e3


;......................................
.pattern.table.chan1.pattern9

  .db $5, $25, $8
  .db $e3
  .db $5, $25, $8
  .db $e3
  .db $5, $25, $8
  .db $e3
  .db $5, $25, $b
  .db $e3
  .db $5, $25, $b
  .db $e3
  .db $d, $25, $5, $1b
  .db $e3
  .db $d, $25, $b, $1d
  .db $e3
  .db $d, $26, $5, $1b
  .db $e3
  .db $d, $26, $b, $1d
  .db $e3
  .db $d, $26, $5, $1b
  .db $e3
  .db $d, $27, $b, $1d
  .db $e3
  .db $5, $27, $b
  .db $f3


;......................................
.pattern.table.chan1.pattern10

  .db $fe
  .db $fe
  .db $e4


;........................................................................
;........................................................................

;......................................
.pattern.table.chan2.pattern0

  .db $7d, $26, $7, $1b, $10, $5, $3, $8, $fd
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan2.pattern1

  .db $5, $25, $7
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan2.pattern2

  .db $5, $25, $7
  .db $fe
  .db $e9
  .db $5, $2a, $7
  .db $e3
  .db $5, $2a, $7
  .db $f3


;......................................
.pattern.table.chan2.pattern3

  .db $e0
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan2.pattern4

  .db $e0
  .db $e3
  .db $7d, $23, $8, $1b, $10, $4, $3, $8, $df
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $d, $28, $8, $1d
  .db $e3
  .db $e0
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $d, $28, $8, $1b
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $d, $22, $8, $1d
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $28, $8
  .db $e3


;......................................
.pattern.table.chan2.pattern5

  .db $e0
  .db $e3
  .db $d, $21, $8, $1b
  .db $e3
  .db $d, $1f, $8, $1d
  .db $e3
  .db $d, $21, $8, $1b
  .db $e3
  .db $d, $23, $8, $1d
  .db $e3
  .db $5, $21, $8
  .db $e3
  .db $5, $1f, $8
  .db $e3
  .db $5, $1c, $8
  .db $e7
  .db $5, $1f, $8
  .db $e7
  .db $d, $21, $8, $1b
  .db $e7
  .db $d, $23, $8, $1d
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $2b, $8
  .db $e3


;......................................
.pattern.table.chan2.pattern6

  .db $d, $26, $5, $1b
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $d, $26, $8, $1d
  .db $e3
  .db $5, $26, $b
  .db $e3
  .db $5, $26, $b
  .db $e3
  .db $5, $26, $8
  .db $e3
  .db $5, $26, $b
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $b
  .db $e3


;......................................
.pattern.table.chan2.pattern7

  .db $d, $28, $5, $1b
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $d, $28, $8, $1d
  .db $e3
  .db $5, $28, $b
  .db $e3
  .db $5, $28, $b
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $28, $b
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $8
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $b
  .db $e3
  .db $5, $27, $b
  .db $e3


;......................................
.pattern.table.chan2.pattern8

  .db $5, $28, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $28, $8
  .db $e3
  .db $5, $28, $b
  .db $e3
  .db $5, $28, $b
  .db $e3
  .db $d, $28, $5, $1b
  .db $e3
  .db $d, $28, $b, $1d
  .db $e3
  .db $d, $29, $5, $1b
  .db $e3
  .db $d, $29, $b, $1d
  .db $e3
  .db $d, $29, $5, $1b
  .db $e3
  .db $d, $2b, $b, $1d
  .db $e3
  .db $5, $2b, $b
  .db $f3


;......................................
.pattern.table.chan2.pattern9

  .db $fe
  .db $fe
  .db $e4


;........................................................................
;........................................................................

;......................................
.pattern.table.chan3.pattern0

  .db $7d, $2b, $7, $1b, $10, $5, $3, $8, $df
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan3.pattern1

  .db $5, $2b, $7
  .db $fe
  .db $e9
  .db $5, $2d, $7
  .db $e3
  .db $5, $2d, $7
  .db $f3


;......................................
.pattern.table.chan3.pattern2

  .db $7d, $1f, $5, $1e, $10, $6, $3, $8, $ff
  .db $e4
  .db $5, $21, $5
  .db $e4
  .db $5, $22, $5
  .db $e5
  .db $5, $23, $5
  .db $e4
  .db $5, $26, $5
  .db $e4
  .db $5, $27, $5
  .db $e4
  .db $30, $b, $5
  .db $fe
  .db $e2


;......................................
.pattern.table.chan3.pattern3

  .db $d, $28, $5, $1e
  .db $ef
  .db $30, $4, $64
  .db $fe
  .db $e5
  .db $d, $28, $9, $18
  .db $e3
  .db $3d, $26, $5, $1e, $4, $0
  .db $e3
  .db $5, $28, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern4

  .db $5, $2d, $5
  .db $e6
  .db $30, $ec, $2
  .db $3d, $2d, $5, $19, $8, $fd
  .db $e7
  .db $3d, $2b, $5, $1e, $8, $ff
  .db $e6
  .db $30, $ec, $2
  .db $3d, $2b, $5, $19, $8, $fd
  .db $e3
  .db $3d, $2a, $5, $1e, $8, $ff
  .db $e6
  .db $30, $ec, $2
  .db $5, $2a, $5
  .db $e3
  .db $5, $29, $5
  .db $e3
  .db $5, $2a, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $2b, $5, $1e
  .db $ea
  .db $30, $ec, $2


;......................................
.pattern.table.chan3.pattern5

  .db $5, $28, $5
  .db $ef
  .db $38, $18, $4, $64
  .db $e2
  .db $30, $ec, $2
  .db $3d, $28, $5, $1e, $4, $0
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $5, $22, $5
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3
  .db $5, $1c, $5
  .db $e3
  .db $5, $1a, $5
  .db $e3
  .db $5, $1c, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3
  .db $5, $21, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern6

  .db $5, $21, $5
  .db $e1
  .db $35, $23, $5, $3, $8
  .db $eb
  .db $d, $23, $9, $18
  .db $30, $ec, $2
  .db $d, $21, $5, $1e
  .db $e1
  .db $35, $23, $5, $3, $8
  .db $e8
  .db $30, $ec, $2
  .db $5, $21, $5
  .db $ef
  .db $30, $4, $64
  .db $e3
  .db $3d, $20, $5, $1d, $4, $0
  .db $5, $1f, $5
  .db $d, $1e, $5, $1b
  .db $5, $1d, $5
  .db $d, $1c, $5, $18
  .db $5, $1b, $5
  .db $d, $1a, $5, $14
  .db $5, $19, $5
  .db $d, $18, $5, $12
  .db $5, $17, $5
  .db $d, $15, $5, $f
  .db $5, $14, $5
  .db $d, $13, $5, $d
  .db $5, $12, $5
  .db $d, $11, $5, $b
  .db $5, $10, $5


;......................................
.pattern.table.chan3.pattern7

  .db $d, $28, $5, $1e
  .db $ef
  .db $8, $18
  .db $e3
  .db $d, $26, $5, $1e
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $2a, $5, $1e
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $28, $5, $1e
  .db $e7
  .db $5, $26, $5
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern8

  .db $5, $21, $5
  .db $e3
  .db $5, $22, $5
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $5, $22, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $23, $5, $1e
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $26, $5, $1e
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $28, $5, $1e
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $2b, $5, $1e
  .db $e6
  .db $30, $ec, $2
  .db $5, $2d, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern9

  .db $5, $2f, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $5
  .db $e3
  .db $5, $2d, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $2b, $5, $1e
  .db $e3
  .db $5, $2a, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $28, $5, $1e
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $26, $5, $1e
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern10

  .db $5, $1f, $5
  .db $35, $21, $5, $3, $f
  .db $ec
  .db $d, $21, $9, $18
  .db $30, $ec, $2
  .db $d, $1c, $5, $1e
  .db $e3
  .db $5, $1f, $5
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $23, $5, $1e
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $26, $5, $1e
  .db $e3
  .db $d, $25, $5, $1d
  .db $5, $24, $5
  .db $d, $23, $5, $1b
  .db $5, $22, $5
  .db $d, $21, $5, $18
  .db $5, $20, $5
  .db $d, $1f, $5, $16
  .db $5, $1e, $5
  .db $d, $1d, $5, $14
  .db $5, $1c, $5
  .db $d, $1b, $5, $12
  .db $5, $1a, $5
  .db $d, $19, $5, $f
  .db $5, $18, $5
  .db $d, $17, $5, $d
  .db $5, $16, $5


;......................................
.pattern.table.chan3.pattern11

  .db $d, $28, $5, $1e
  .db $ef
  .db $8, $18
  .db $e3
  .db $d, $23, $5, $1e
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $2b, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern12

  .db $5, $28, $5
  .db $eb
  .db $30, $4, $84
  .db $e3
  .db $8, $18
  .db $e2
  .db $30, $ec, $2
  .db $3d, $28, $5, $1e, $4, $0
  .db $e3
  .db $5, $2b, $5
  .db $e3
  .db $5, $2d, $5
  .db $e3
  .db $5, $2e, $5
  .db $e3
  .db $5, $2f, $5
  .db $e3
  .db $5, $32, $5
  .db $e3
  .db $5, $34, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $32, $5
  .db $e3
  .db $5, $34, $5
  .db $e3
  .db $5, $37, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern13

  .db $5, $39, $5
  .db $e1
  .db $35, $3b, $5, $3, $8
  .db $eb
  .db $d, $3b, $9, $18
  .db $30, $ec, $2
  .db $d, $39, $5, $1e
  .db $e1
  .db $35, $3b, $5, $3, $8
  .db $e8
  .db $30, $ec, $2
  .db $5, $39, $5
  .db $eb
  .db $30, $4, $64
  .db $e7
  .db $3d, $38, $5, $1d, $4, $0
  .db $5, $37, $5
  .db $d, $36, $5, $1b
  .db $5, $35, $5
  .db $d, $34, $5, $18
  .db $5, $33, $5
  .db $d, $32, $5, $16
  .db $5, $31, $5
  .db $d, $30, $5, $14
  .db $5, $2f, $5
  .db $d, $2e, $5, $12
  .db $5, $2d, $5
  .db $d, $2c, $5, $f
  .db $5, $2b, $5
  .db $d, $2a, $5, $d
  .db $5, $29, $5


;......................................
.pattern.table.chan3.pattern14

  .db $3d, $2f, $7, $1b, $10, $a
  .db $e3
  .db $5, $2f, $7
  .db $e3
  .db $5, $2f, $7
  .db $d, $2f, $b, $18
  .db $e2
  .db $d, $2f, $7, $1b
  .db $d, $2f, $b, $18
  .db $e2
  .db $d, $2f, $7, $1b
  .db $d, $2f, $b, $18
  .db $e2
  .db $d, $2f, $7, $1b
  .db $e3
  .db $d, $2f, $7, $1b
  .db $d, $2f, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $e3
  .db $5, $30, $7
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $e3
  .db $5, $30, $7
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $e3
  .db $5, $30, $7
  .db $e3
  .db $5, $30, $7
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $d, $30, $b, $18
  .db $e2


;......................................
.pattern.table.chan3.pattern15

  .db $d, $31, $7, $1b
  .db $e3
  .db $5, $31, $7
  .db $e3
  .db $5, $31, $7
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $31, $7, $1b
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $31, $7, $1b
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $31, $7, $1b
  .db $e3
  .db $d, $31, $7, $1b
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $e3
  .db $5, $30, $7
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $e3
  .db $5, $30, $7
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $e3
  .db $5, $30, $7
  .db $e3
  .db $5, $30, $7
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $d, $30, $b, $18
  .db $e2
  .db $d, $30, $7, $1b
  .db $d, $30, $b, $18
  .db $e2


;......................................
.pattern.table.chan3.pattern16

  .db $d, $31, $7, $1b
  .db $e3
  .db $5, $31, $7
  .db $e3
  .db $5, $31, $7
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $31, $7, $1b
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $31, $7, $1b
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $31, $7, $1b
  .db $e3
  .db $d, $31, $7, $1b
  .db $d, $31, $b, $18
  .db $e2
  .db $d, $32, $7, $1b
  .db $e3
  .db $5, $32, $7
  .db $d, $32, $b, $18
  .db $e2
  .db $d, $32, $7, $1b
  .db $d, $32, $b, $18
  .db $e2
  .db $3d, $32, $7, $1b, $10, $5
  .db $e3
  .db $5, $32, $7
  .db $f3


;......................................
.pattern.table.chan3.pattern17

  .db $d, $32, $9, $17
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan3.pattern18

  .db $3d, $2f, $5, $1e, $10, $b
  .db $e2
  .db $35, $32, $5, $ed, $1
  .db $e1
  .db $35, $2f, $5, $ed, $2
  .db $e2
  .db $5, $32, $5
  .db $e2
  .db $35, $2f, $5, $ed, $1
  .db $e1
  .db $35, $32, $5, $ed, $2
  .db $e2
  .db $5, $2f, $5
  .db $e2
  .db $35, $32, $5, $ed, $1
  .db $e1
  .db $35, $2f, $5, $ed, $2
  .db $e2
  .db $5, $32, $5
  .db $e2
  .db $35, $2f, $5, $ed, $1
  .db $e1
  .db $35, $32, $5, $ed, $2
  .db $e2
  .db $35, $34, $5, $3, $3
  .db $e7
  .db $40, $3, $4, $64
  .db $e6
  .db $30, $ec, $2
  .db $45, $2f, $5, $3, $4, $0
  .db $e3
  .db $5, $2d, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3
  .db $5, $28, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern19

  .db $5, $2b, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $3d, $28, $5, $1a, $8, $df
  .db $e3
  .db $3d, $25, $5, $1e, $8, $ff
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $27, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $5
  .db $e3
  .db $5, $2d, $5
  .db $e3
  .db $5, $2f, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern20

  .db $5, $2e, $5
  .db $e3
  .db $5, $2f, $5
  .db $e3
  .db $5, $37, $5
  .db $e3
  .db $5, $2e, $5
  .db $e3
  .db $5, $2f, $5
  .db $e3
  .db $5, $37, $5
  .db $e3
  .db $5, $36, $5
  .db $e3
  .db $5, $34, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $32, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $31, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $2f, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $2d, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern21

  .db $5, $2e, $5
  .db $e3
  .db $5, $2d, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3
  .db $5, $2b, $5
  .db $e1
  .db $35, $2d, $5, $3, $4
  .db $e5
  .db $30, $4, $64
  .db $ed
  .db $8, $18
  .db $e5
  .db $8, $16
  .db $e3
  .db $8, $14
  .db $e3


;......................................
.pattern.table.chan3.pattern22

  .db $7d, $32, $5, $1d, $10, $c, $3, $4, $0
  .db $e2
  .db $35, $34, $5, $ed, $1
  .db $e1
  .db $35, $37, $5, $ed, $2
  .db $e2
  .db $5, $39, $5
  .db $e2
  .db $35, $37, $5, $ed, $1
  .db $e1
  .db $35, $34, $5, $ed, $2
  .db $e2
  .db $35, $32, $5, $10, $c
  .db $e2
  .db $35, $34, $5, $ed, $1
  .db $e1
  .db $35, $37, $5, $ed, $2
  .db $e2
  .db $5, $39, $5
  .db $e2
  .db $35, $37, $5, $ed, $1
  .db $e1
  .db $35, $34, $5, $ed, $2
  .db $e2
  .db $5, $32, $5
  .db $e3
  .db $5, $34, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $37, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $39, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $3b, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern23

  .db $5, $3d, $5
  .db $e3
  .db $5, $3b, $5
  .db $e3
  .db $5, $37, $5
  .db $e3
  .db $5, $31, $5
  .db $e3
  .db $5, $2f, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $5, $22, $5
  .db $e3
  .db $5, $23, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $27, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern24

  .db $5, $2b, $5
  .db $35, $2d, $5, $ed, $1
  .db $e6
  .db $5, $2b, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $2d, $5, $1d
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $2b, $5
  .db $35, $2d, $5, $ed, $1
  .db $e2


;......................................
.pattern.table.chan3.pattern25

  .db $e8
  .db $5, $2b, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $2d, $5, $1d
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $26, $5
  .db $e3
  .db $5, $28, $5
  .db $e3
  .db $5, $2b, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern26

  .db $3d, $28, $c, $1e, $10, $b
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan3.pattern27

  .db $5, $2d, $d
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan3.pattern28

  .db $5, $2d, $5
  .db $35, $2f, $5, $3, $2
  .db $e5
  .db $30, $ec, $2
  .db $5, $32, $5
  .db $e3
  .db $5, $2d, $5
  .db $35, $2f, $5, $3, $2
  .db $e5
  .db $30, $ec, $2
  .db $5, $32, $5
  .db $e3
  .db $5, $2d, $5
  .db $35, $2f, $5, $3, $2
  .db $e5
  .db $30, $ec, $2
  .db $5, $32, $5
  .db $e3
  .db $5, $2d, $5
  .db $35, $2f, $5, $3, $2
  .db $e5
  .db $30, $ec, $2
  .db $5, $32, $5
  .db $e3
  .db $5, $2d, $5
  .db $35, $2f, $5, $3, $2
  .db $e5
  .db $30, $ec, $2
  .db $35, $32, $5, $3, $0
  .db $e3
  .db $5, $34, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern29

  .db $5, $37, $5
  .db $e3
  .db $8, $18
  .db $e3
  .db $d, $37, $5, $1e
  .db $e3
  .db $5, $34, $5
  .db $e3
  .db $5, $37, $5
  .db $e1
  .db $35, $39, $5, $3, $2
  .db $e5
  .db $30, $4, $64
  .db $e7
  .db $8, $1d
  .db $e7
  .db $8, $17
  .db $e3
  .db $8, $16
  .db $e3
  .db $31, $e0, $4, $0
  .db $e3
  .db $3d, $3a, $5, $1d, $10, $c
  .db $e3
  .db $5, $39, $5
  .db $e3
  .db $5, $37, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern30

  .db $5, $34, $5
  .db $e2
  .db $35, $32, $5, $ed, $1
  .db $e1
  .db $35, $2f, $5, $ed, $2
  .db $e2
  .db $5, $32, $5
  .db $e2
  .db $35, $2f, $5, $ed, $1
  .db $e1
  .db $35, $2d, $5, $ed, $2
  .db $e2
  .db $5, $2f, $5
  .db $e2
  .db $35, $2d, $5, $ed, $1
  .db $e1
  .db $35, $2b, $5, $ed, $2
  .db $e2
  .db $5, $2d, $5
  .db $e2
  .db $35, $2b, $5, $ed, $1
  .db $e1
  .db $35, $28, $5, $ed, $2
  .db $e2
  .db $5, $2b, $5
  .db $e2
  .db $35, $28, $5, $ed, $1
  .db $e1
  .db $35, $26, $5, $ed, $2
  .db $e2
  .db $5, $28, $5
  .db $e2
  .db $35, $26, $5, $ed, $1
  .db $e1
  .db $35, $23, $5, $ed, $2
  .db $e2
  .db $5, $26, $5
  .db $e2
  .db $35, $23, $5, $ed, $1
  .db $e1
  .db $35, $21, $5, $ed, $2
  .db $e2
  .db $5, $23, $5
  .db $e2
  .db $35, $21, $5, $ed, $1
  .db $e1
  .db $35, $1f, $5, $ed, $2
  .db $e2


;......................................
.pattern.table.chan3.pattern31

  .db $5, $21, $5
  .db $e3
  .db $35, $22, $5, $3, $f
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $5, $1f, $5
  .db $e3
  .db $5, $21, $5
  .db $e3
  .db $5, $23, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $5
  .db $e6
  .db $30, $ec, $2
  .db $5, $2d, $5
  .db $e3
  .db $5, $2f, $5
  .db $e3
  .db $5, $32, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern32

  .db $5, $34, $5
  .db $e1
  .db $5, $2f, $5
  .db $e1
  .db $5, $2c, $5
  .db $e1
  .db $5, $28, $5
  .db $e1
  .db $5, $33, $5
  .db $e1
  .db $5, $2e, $5
  .db $e1
  .db $5, $2b, $5
  .db $e1
  .db $5, $27, $5
  .db $e1
  .db $5, $32, $5
  .db $e1
  .db $5, $2d, $5
  .db $e1
  .db $5, $2a, $5
  .db $e1
  .db $5, $26, $5
  .db $e1
  .db $5, $31, $5
  .db $e1
  .db $5, $2c, $5
  .db $e1
  .db $5, $29, $5
  .db $e1
  .db $5, $25, $5
  .db $e1
  .db $5, $30, $5
  .db $e1
  .db $5, $2b, $5
  .db $e1
  .db $5, $28, $5
  .db $e1
  .db $5, $24, $5
  .db $e1
  .db $5, $2f, $5
  .db $e1
  .db $5, $2a, $5
  .db $e1
  .db $5, $27, $5
  .db $e1
  .db $5, $23, $5
  .db $e1
  .db $5, $2e, $5
  .db $e1
  .db $5, $29, $5
  .db $e1
  .db $5, $26, $5
  .db $e1
  .db $5, $22, $5
  .db $e1
  .db $5, $2d, $5
  .db $e1
  .db $5, $28, $5
  .db $e1
  .db $5, $25, $5
  .db $e1
  .db $5, $21, $5
  .db $e1


;......................................
.pattern.table.chan3.pattern33

  .db $5, $2c, $5
  .db $e1
  .db $5, $27, $5
  .db $e1
  .db $5, $24, $5
  .db $e1
  .db $5, $20, $5
  .db $e1
  .db $5, $2b, $5
  .db $e1
  .db $5, $26, $5
  .db $e1
  .db $5, $23, $5
  .db $e1
  .db $5, $1f, $5
  .db $e1
  .db $5, $2a, $5
  .db $e1
  .db $5, $25, $5
  .db $e1
  .db $5, $22, $5
  .db $e1
  .db $5, $1e, $5
  .db $e1
  .db $5, $29, $5
  .db $e1
  .db $5, $24, $5
  .db $e1
  .db $5, $21, $5
  .db $e1
  .db $5, $1d, $5
  .db $e1
  .db $5, $1c, $5
  .db $35, $1b, $5, $ed, $1
  .db $5, $1a, $5
  .db $35, $19, $5, $ed, $1
  .db $5, $18, $5
  .db $35, $17, $5, $ed, $1
  .db $5, $16, $5
  .db $35, $15, $5, $ed, $1
  .db $5, $14, $5
  .db $35, $13, $5, $ed, $1
  .db $5, $12, $5
  .db $35, $11, $5, $ed, $1
  .db $5, $10, $5
  .db $35, $f, $5, $ed, $1
  .db $5, $e, $5
  .db $35, $d, $5, $ed, $1
  .db $5, $c, $5
  .db $5, $b, $5
  .db $5, $a, $5
  .db $5, $9, $5
  .db $5, $8, $5
  .db $5, $7, $5
  .db $5, $6, $5
  .db $5, $5, $5
  .db $5, $4, $5
  .db $5, $3, $5
  .db $5, $2, $5
  .db $5, $1, $5
  .db $e0
  .db $e3


;........................................................................
;........................................................................

;......................................
.pattern.table.chan4.pattern0

  .db $7d, $2a, $7, $1b, $10, $5, $3, $8, $fd
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan4.pattern1

  .db $e0
  .db $fe
  .db $fe
  .db $e3


;......................................
.pattern.table.chan4.pattern2

  .db $7d, $2a, $7, $18, $10, $a, $3, $8, $ff
  .db $e3
  .db $5, $2a, $7
  .db $e3
  .db $5, $2a, $7
  .db $d, $2a, $b, $14
  .db $e2
  .db $d, $2a, $7, $18
  .db $d, $2a, $b, $14
  .db $e2
  .db $d, $2a, $7, $18
  .db $d, $2a, $b, $14
  .db $e2
  .db $d, $2a, $7, $18
  .db $e3
  .db $d, $2a, $7, $18
  .db $d, $2a, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $e3
  .db $5, $2b, $7
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $e3
  .db $5, $2b, $7
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $e3
  .db $5, $2b, $7
  .db $e3
  .db $5, $2b, $7
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $d, $2b, $b, $14
  .db $e2


;......................................
.pattern.table.chan4.pattern3

  .db $d, $2c, $7, $18
  .db $e3
  .db $5, $2c, $7
  .db $e3
  .db $5, $2c, $7
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2c, $7, $18
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2c, $7, $18
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2c, $7, $18
  .db $e3
  .db $d, $2c, $7, $18
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $e3
  .db $5, $2b, $7
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $e3
  .db $5, $2b, $7
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $e3
  .db $5, $2b, $7
  .db $e3
  .db $5, $2b, $7
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $d, $2b, $b, $14
  .db $e2
  .db $d, $2b, $7, $18
  .db $d, $2b, $b, $14
  .db $e2


;......................................
.pattern.table.chan4.pattern4

  .db $d, $2c, $7, $18
  .db $e3
  .db $5, $2c, $7
  .db $e3
  .db $5, $2c, $7
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2c, $7, $18
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2c, $7, $18
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2c, $7, $18
  .db $e3
  .db $d, $2c, $7, $18
  .db $d, $2c, $b, $14
  .db $e2
  .db $d, $2d, $7, $18
  .db $e3
  .db $5, $2d, $7
  .db $d, $2d, $b, $14
  .db $e2
  .db $d, $2d, $7, $18
  .db $d, $2d, $b, $14
  .db $e2
  .db $3d, $2d, $7, $1b, $10, $5
  .db $e3
  .db $5, $2d, $7
  .db $f3


;......................................
.pattern.table.chan4.pattern5

  .db $d, $2d, $9, $17
  .db $fe
  .db $fe
  .db $e3


;........................................................................
;........................................................................

;......................................
.pattern.table.chan5.pattern0

  .db $7d, $2f, $7, $1b, $10, $5, $f, $8, $df, $9, $1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e4


;......................................
.pattern.table.chan5.pattern1

  .db $5, $2f, $7
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e5
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $e4
  .db $7d, $c, $2, $1f, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $f, $d, $0, $f, $3
  .db $f0


;......................................
.pattern.table.chan5.pattern2

  .db $75, $18, $2, $11, $0, $3, $8, $ff
  .db $40, $c, $f, $1
  .db $30, $11, $1
  .db $e2
  .db $35, $18, $2, $11, $0
  .db $e1
  .db $30, $11, $1
  .db $e2
  .db $35, $18, $2, $11, $0
  .db $e1
  .db $30, $11, $1
  .db $e3
  .db $35, $18, $2, $11, $0
  .db $e1
  .db $30, $11, $1
  .db $e2
  .db $35, $18, $2, $11, $0
  .db $e1
  .db $30, $11, $1
  .db $e2
  .db $35, $18, $2, $11, $0
  .db $e1
  .db $30, $11, $1
  .db $e2
  .db $40, $c, $d, $0
  .db $fe
  .db $e2


;......................................
.pattern.table.chan5.pattern3

  .db $75, $c, $0, $11, $1, $3, $8, $ff
  .db $75, $c, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $3
  .db $e3
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $c, $0, $3, $8, $ff
  .db $35, $c, $1, $11, $0
  .db $e2
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $45, $c, $0, $3, $8, $ff
  .db $35, $c, $1, $11, $0
  .db $e2
  .db $35, $c, $0, $11, $1
  .db $75, $c, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $3
  .db $e3


;......................................
.pattern.table.chan5.pattern4

  .db $75, $c, $0, $11, $1, $3, $8, $ff
  .db $75, $c, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $3
  .db $e3
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $0
  .db $35, $17, $4, $11, $0
  .db $e2
  .db $35, $c, $3, $11, $1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $0
  .db $35, $17, $4, $11, $0
  .db $e2
  .db $35, $c, $3, $11, $1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $0
  .db $35, $17, $4, $11, $0
  .db $e2
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $3
  .db $e3


;......................................
.pattern.table.chan5.pattern5

  .db $75, $c, $0, $11, $1, $3, $8, $ff
  .db $75, $c, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $3
  .db $e3
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $c, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $0
  .db $35, $17, $4, $11, $0
  .db $e2
  .db $35, $c, $3, $11, $1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $0
  .db $35, $17, $4, $11, $0
  .db $e2
  .db $35, $c, $3, $11, $1
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $c, $0
  .db $35, $17, $4, $11, $0
  .db $e2
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3


;......................................
.pattern.table.chan5.pattern6

  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $30, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $75, $2e, $a, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $30, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $75, $2e, $a, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $30, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $75, $2e, $a, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $30, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $75, $2e, $a, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3


;......................................
.pattern.table.chan5.pattern7

  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $30, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $75, $2e, $a, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $ff
  .db $75, $30, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $30, $0, $11, $1, $3, $8, $df
  .db $75, $2e, $a, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $75, $30, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $30, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $5, $30, $3
  .db $e3
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $c, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $70, $d, $0, $c, $f, $3
  .db $f0




