

;###########################################################################
.patternList.table
  .dw .patternList.chan0
  .dw .patternList.chan1
  .dw .patternList.chan2
  .dw .patternList.chan3
  .dw .patternList.chan4
  .dw .patternList.chan5

.patternList.chan0
  .db 0
  .db 1
  .db 2
  .db 3
  .db 2
  .db 4
  .db 5
  .db 6
  .db 7
  .db 8
.patternList.chan1
  .db 0
  .db 1
  .db 2
  .db 3
  .db 2
  .db 4
  .db 5
  .db 6
  .db 7
  .db 8
.patternList.chan2
  .db 0
  .db 1
  .db 2
  .db 3
  .db 2
  .db 4
  .db 5
  .db 6
  .db 7
  .db 8
.patternList.chan3
  .db 0
  .db 1
  .db 2
  .db 2
  .db 2
  .db 2
  .db 3
  .db 3
  .db 4
  .db 5
.patternList.chan4
  .db 0
  .db 0
  .db 0
  .db 0
  .db 0
  .db 0
  .db 1
  .db 2
  .db 3
  .db 4
.patternList.chan5
  .db 0
  .db 1
  .db 2
  .db 2
  .db 2
  .db 3
  .db 4
  .db 5
  .db 6
  .db 7


