

;###########################################################################
.pattern.table
  .dw .pattern.table.chan0
  .dw .pattern.table.chan1
  .dw .pattern.table.chan2
  .dw .pattern.table.chan3
  .dw .pattern.table.chan4
  .dw .pattern.table.chan5


;.....................................................
.pattern.table.chan0
  .dw .pattern.table.chan0.pattern0
  .dw .pattern.table.chan0.pattern1
  .dw .pattern.table.chan0.pattern2
  .dw .pattern.table.chan0.pattern3
  .dw .pattern.table.chan0.pattern4
  .dw .pattern.table.chan0.pattern5
  .dw .pattern.table.chan0.pattern6
  .dw .pattern.table.chan0.pattern7
  .dw .pattern.table.chan0.pattern8
;.....................................................
.pattern.table.chan1
  .dw .pattern.table.chan1.pattern0
  .dw .pattern.table.chan1.pattern1
  .dw .pattern.table.chan1.pattern2
  .dw .pattern.table.chan1.pattern3
  .dw .pattern.table.chan1.pattern4
  .dw .pattern.table.chan1.pattern5
  .dw .pattern.table.chan1.pattern6
  .dw .pattern.table.chan1.pattern7
  .dw .pattern.table.chan1.pattern8
;.....................................................
.pattern.table.chan2
  .dw .pattern.table.chan2.pattern0
  .dw .pattern.table.chan2.pattern1
  .dw .pattern.table.chan2.pattern2
  .dw .pattern.table.chan2.pattern3
  .dw .pattern.table.chan2.pattern4
  .dw .pattern.table.chan2.pattern5
  .dw .pattern.table.chan2.pattern6
  .dw .pattern.table.chan2.pattern7
  .dw .pattern.table.chan2.pattern8
;.....................................................
.pattern.table.chan3
  .dw .pattern.table.chan3.pattern0
  .dw .pattern.table.chan3.pattern1
  .dw .pattern.table.chan3.pattern2
  .dw .pattern.table.chan3.pattern3
  .dw .pattern.table.chan3.pattern4
  .dw .pattern.table.chan3.pattern5
;.....................................................
.pattern.table.chan4
  .dw .pattern.table.chan4.pattern0
  .dw .pattern.table.chan4.pattern1
  .dw .pattern.table.chan4.pattern2
  .dw .pattern.table.chan4.pattern3
  .dw .pattern.table.chan4.pattern4
;.....................................................
.pattern.table.chan5
  .dw .pattern.table.chan5.pattern0
  .dw .pattern.table.chan5.pattern1
  .dw .pattern.table.chan5.pattern2
  .dw .pattern.table.chan5.pattern3
  .dw .pattern.table.chan5.pattern4
  .dw .pattern.table.chan5.pattern5
  .dw .pattern.table.chan5.pattern6
  .dw .pattern.table.chan5.pattern7


;###########################################################################


;........................................................................
;........................................................................

;......................................
.pattern.table.chan0.pattern0

  .db $35, $c, $6, $10, $3
  .db $e3
  .db $e0
  .db $e3
  .db $5, $13, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $1a, $6
  .db $e3
  .db $e0
  .db $e3
  .db $5, $18, $6
  .db $ea
  .db $30, $ec, $2
  .db $5, $11, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $12, $6
  .db $e3
  .db $e0
  .db $e3
  .db $5, $13, $6
  .db $fe
  .db $f5


;......................................
.pattern.table.chan0.pattern1

  .db $f8
  .db $e0
  .db $ef
  .db $3d, $2b, $a, $1d, $10, $7
  .db $e7
  .db $d, $37, $a, $1d
  .db $f7
  .db $3d, $13, $6, $1f, $10, $3
  .db $ef
  .db $e0
  .db $e7


;......................................
.pattern.table.chan0.pattern2

  .db $e0
  .db $f3
  .db $3d, $c, $7, $1d, $10, $4
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $eb
  .db $e0
  .db $f3
  .db $5, $11, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $eb


;......................................
.pattern.table.chan0.pattern3

  .db $e0
  .db $f3
  .db $3d, $c, $7, $1d, $10, $4
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $eb
  .db $e0
  .db $f3
  .db $5, $7, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $7
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $eb


;......................................
.pattern.table.chan0.pattern4

  .db $e0
  .db $f3
  .db $3d, $c, $7, $1d, $10, $4
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $eb
  .db $5, $c, $7
  .db $eb
  .db $e0
  .db $e7
  .db $35, $30, $c, $10, $7
  .db $e3
  .db $5, $3c, $c
  .db $f1
  .db $d, $48, $9, $f
  .db $e5


;......................................
.pattern.table.chan0.pattern5

  .db $3d, $11, $7, $1d, $10, $4
  .db $ea
  .db $30, $ec, $2
  .db $5, $11, $7
  .db $eb
  .db $e0
  .db $eb
  .db $7d, $29, $d, $1a, $10, $8, $3, $8, $fd
  .db $ea
  .db $30, $ec, $2
  .db $7d, $10, $7, $1d, $10, $4, $3, $8, $ff
  .db $ea
  .db $30, $ec, $2
  .db $5, $10, $7
  .db $eb
  .db $e0
  .db $eb
  .db $7d, $28, $d, $1a, $10, $8, $3, $8, $fd
  .db $eb


;......................................
.pattern.table.chan0.pattern6

  .db $7d, $e, $7, $1d, $10, $4, $3, $8, $ff
  .db $ea
  .db $30, $ec, $2
  .db $5, $e, $7
  .db $eb
  .db $e0
  .db $eb
  .db $7d, $26, $d, $1a, $10, $8, $3, $8, $fd
  .db $eb
  .db $7d, $c, $7, $1d, $10, $4, $3, $8, $ff
  .db $ea
  .db $30, $ec, $2
  .db $5, $c, $7
  .db $eb
  .db $e0
  .db $eb
  .db $7d, $28, $d, $1a, $10, $8, $3, $8, $fd
  .db $eb


;......................................
.pattern.table.chan0.pattern7

  .db $7d, $11, $7, $1d, $10, $4, $3, $8, $ff
  .db $ea
  .db $30, $ec, $2
  .db $5, $11, $7
  .db $eb
  .db $e0
  .db $eb
  .db $7d, $29, $d, $1a, $10, $8, $3, $8, $fd
  .db $eb
  .db $7d, $12, $7, $1d, $10, $4, $3, $8, $ff
  .db $ea
  .db $30, $ec, $2
  .db $5, $12, $7
  .db $eb
  .db $e0
  .db $eb
  .db $7d, $2a, $d, $1a, $10, $8, $3, $8, $fd
  .db $eb


;......................................
.pattern.table.chan0.pattern8

  .db $7d, $13, $7, $1d, $10, $4, $3, $8, $ff
  .db $ea
  .db $30, $ec, $2
  .db $5, $15, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $16, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $17, $7
  .db $ea
  .db $30, $ec, $2
  .db $5, $13, $7
  .db $eb
  .db $e0
  .db $eb
  .db $5, $6, $7
  .db $eb
  .db $e0
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan1.pattern0

  .db $3d, $1f, $8, $1d, $10, $5
  .db $e3
  .db $5, $1f, $9
  .db $e3
  .db $5, $2b, $8
  .db $e3
  .db $5, $37, $8
  .db $e3
  .db $5, $37, $9
  .db $e3
  .db $5, $35, $8
  .db $e7
  .db $5, $35, $9
  .db $e3
  .db $5, $2d, $8
  .db $e3
  .db $5, $2e, $8
  .db $e3
  .db $5, $2e, $9
  .db $e3
  .db $5, $2f, $8
  .db $fe
  .db $f5


;......................................
.pattern.table.chan1.pattern1

  .db $f8
  .db $5, $2f, $9
  .db $ef
  .db $35, $37, $a, $10, $7
  .db $e7
  .db $5, $43, $a
  .db $fe
  .db $f1


;......................................
.pattern.table.chan1.pattern2

  .db $e8
  .db $3d, $34, $b, $1d, $10, $6
  .db $e3
  .db $5, $34, $9
  .db $e7
  .db $5, $33, $b
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $b
  .db $eb
  .db $d, $34, $9, $18
  .db $e7
  .db $d, $33, $b, $1d
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $b
  .db $ea
  .db $30, $ec, $2
  .db $5, $2d, $b
  .db $e3
  .db $5, $2d, $9
  .db $e2
  .db $30, $ec, $2
  .db $5, $30, $b
  .db $ef
  .db $e0
  .db $eb


;......................................
.pattern.table.chan1.pattern3

  .db $e8
  .db $5, $34, $b
  .db $e3
  .db $5, $34, $9
  .db $e7
  .db $5, $33, $b
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $34, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $30, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $32, $b
  .db $eb
  .db $8, $1c
  .db $e1
  .db $8, $1a
  .db $e1
  .db $8, $d
  .db $e1
  .db $8, $b
  .db $e1
  .db $3d, $37, $c, $1d, $10, $7
  .db $e1
  .db $5, $39, $c
  .db $e1
  .db $5, $37, $c
  .db $eb
  .db $e0
  .db $eb


;......................................
.pattern.table.chan1.pattern4

  .db $e8
  .db $d, $34, $b, $1d
  .db $e3
  .db $5, $34, $9
  .db $e7
  .db $5, $34, $b
  .db $e2
  .db $30, $ec, $2
  .db $5, $34, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $2d, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $30, $b
  .db $eb
  .db $8, $1c
  .db $e1
  .db $8, $1a
  .db $e1
  .db $8, $d
  .db $e1
  .db $8, $b
  .db $e1
  .db $8, $9
  .db $e1
  .db $8, $7
  .db $e1
  .db $e0
  .db $f7


;......................................
.pattern.table.chan1.pattern5

  .db $3d, $2d, $c, $1d, $10, $5
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $3d, $41, $c, $1a, $10, $7
  .db $e3
  .db $5, $39, $c
  .db $eb
  .db $3d, $2b, $c, $1d, $10, $5
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $3d, $40, $c, $1a, $10, $7
  .db $e3
  .db $5, $37, $c
  .db $eb


;......................................
.pattern.table.chan1.pattern6

  .db $3d, $29, $c, $1d, $10, $5
  .db $e3
  .db $5, $29, $9
  .db $e3
  .db $5, $29, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $3d, $3e, $c, $1a, $10, $7
  .db $e3
  .db $5, $35, $c
  .db $eb
  .db $3d, $28, $c, $1d, $10, $5
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $c
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $c
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $3d, $3c, $c, $1a, $10, $7
  .db $e3
  .db $5, $34, $c
  .db $eb


;......................................
.pattern.table.chan1.pattern7

  .db $3d, $2d, $c, $1d, $10, $5
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $3d, $41, $c, $1a, $10, $7
  .db $e3
  .db $5, $39, $c
  .db $eb
  .db $3d, $2d, $c, $1d, $10, $5
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $c
  .db $e3
  .db $5, $30, $9
  .db $e7
  .db $3d, $42, $c, $1a, $10, $7
  .db $e3
  .db $5, $39, $c
  .db $eb


;......................................
.pattern.table.chan1.pattern8

  .db $3d, $2f, $c, $1c, $10, $5
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $2f, $c
  .db $e3
  .db $d, $30, $c, $1c
  .db $e3
  .db $5, $30, $9
  .db $e3
  .db $5, $30, $c
  .db $e3
  .db $d, $31, $c, $1d
  .db $e3
  .db $5, $31, $9
  .db $e3
  .db $5, $31, $c
  .db $e3
  .db $d, $32, $c, $1e
  .db $e3
  .db $5, $32, $9
  .db $e3
  .db $5, $32, $c
  .db $e3
  .db $5, $32, $9
  .db $e7
  .db $d, $37, $c, $1d
  .db $e3
  .db $5, $37, $9
  .db $eb
  .db $5, $37, $c
  .db $eb
  .db $d, $37, $9, $14
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan2.pattern0

  .db $7d, $13, $8, $1d, $10, $5, $3, $8, $fb
  .db $e3
  .db $5, $13, $9
  .db $e3
  .db $5, $17, $8
  .db $e3
  .db $5, $23, $8
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $21, $8
  .db $e7
  .db $5, $21, $9
  .db $e3
  .db $5, $18, $8
  .db $e3
  .db $5, $19, $8
  .db $e3
  .db $5, $19, $9
  .db $e3
  .db $5, $1a, $8
  .db $fe
  .db $f5


;......................................
.pattern.table.chan2.pattern1

  .db $f8
  .db $5, $1a, $9
  .db $ef
  .db $5, $2b, $c
  .db $e7
  .db $5, $37, $c
  .db $f7
  .db $5, $13, $c
  .db $f7


;......................................
.pattern.table.chan2.pattern2

  .db $e0
  .db $e7
  .db $7d, $2b, $b, $1c, $10, $6, $3, $8, $ff
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $b
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $eb
  .db $d, $2b, $9, $18
  .db $e7
  .db $d, $2b, $b, $1c
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $ea
  .db $30, $ec, $2
  .db $5, $29, $b
  .db $e3
  .db $5, $29, $9
  .db $e2
  .db $30, $ec, $2
  .db $5, $28, $b
  .db $ef
  .db $e0
  .db $eb


;......................................
.pattern.table.chan2.pattern3

  .db $e8
  .db $7d, $2b, $b, $1c, $10, $6, $3, $8, $ff
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $b
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $29, $b
  .db $eb
  .db $8, $1b
  .db $e1
  .db $8, $19
  .db $e1
  .db $8, $c
  .db $e1
  .db $8, $a
  .db $e1
  .db $8, $8
  .db $e1
  .db $8, $6
  .db $e1
  .db $e0
  .db $f7


;......................................
.pattern.table.chan2.pattern4

  .db $e8
  .db $5, $2b, $b
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $2b, $b
  .db $e2
  .db $30, $ec, $2
  .db $5, $2b, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $26, $b
  .db $e6
  .db $30, $ec, $2
  .db $5, $28, $b
  .db $eb
  .db $8, $1b
  .db $e1
  .db $8, $19
  .db $e1
  .db $8, $c
  .db $e1
  .db $8, $a
  .db $e1
  .db $8, $8
  .db $e1
  .db $8, $6
  .db $e1
  .db $e0
  .db $f7


;......................................
.pattern.table.chan2.pattern5

  .db $3d, $29, $c, $1d, $10, $5
  .db $e3
  .db $5, $29, $9
  .db $e3
  .db $5, $29, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $3d, $35, $c, $1a, $10, $7
  .db $e3
  .db $5, $2d, $c
  .db $eb
  .db $3d, $28, $c, $1d, $10, $5
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $c
  .db $e3
  .db $5, $2b, $c
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2b, $c
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $3d, $34, $c, $1a, $10, $7
  .db $e3
  .db $5, $2b, $c
  .db $eb


;......................................
.pattern.table.chan2.pattern6

  .db $3d, $26, $c, $1d, $10, $5
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $26, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $29, $c
  .db $e3
  .db $5, $29, $9
  .db $e3
  .db $5, $29, $c
  .db $e3
  .db $5, $29, $9
  .db $e7
  .db $3d, $32, $c, $1a, $10, $7
  .db $e3
  .db $5, $2d, $c
  .db $eb
  .db $3d, $24, $c, $1d, $10, $5
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $5, $24, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $28, $c
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $c
  .db $e3
  .db $5, $28, $9
  .db $e7
  .db $3d, $30, $c, $1a, $10, $7
  .db $e3
  .db $5, $2b, $c
  .db $eb


;......................................
.pattern.table.chan2.pattern7

  .db $3d, $29, $c, $1d, $10, $5
  .db $e3
  .db $5, $29, $9
  .db $e3
  .db $5, $29, $c
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $3d, $35, $c, $1a, $10, $7
  .db $e3
  .db $5, $2d, $c
  .db $eb
  .db $3d, $2a, $c, $1d, $10, $5
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $c
  .db $e3
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2d, $c
  .db $e3
  .db $5, $2d, $9
  .db $e7
  .db $3d, $36, $c, $1a, $10, $7
  .db $e3
  .db $5, $2d, $c
  .db $eb


;......................................
.pattern.table.chan2.pattern8

  .db $3d, $26, $c, $1c, $10, $5
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $26, $c
  .db $e3
  .db $d, $28, $c, $1c
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $28, $c
  .db $e3
  .db $d, $29, $c, $1d
  .db $e3
  .db $5, $29, $9
  .db $e3
  .db $5, $29, $c
  .db $e3
  .db $d, $2a, $c, $1e
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2a, $c
  .db $e3
  .db $5, $2a, $9
  .db $e7
  .db $d, $2f, $c, $1d
  .db $e3
  .db $5, $2f, $9
  .db $eb
  .db $5, $2f, $c
  .db $eb
  .db $d, $2f, $9, $14
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan3.pattern0

  .db $3d, $13, $c, $1d, $10, $5
  .db $e3
  .db $5, $13, $9
  .db $e3
  .db $5, $1f, $c
  .db $e3
  .db $5, $2b, $c
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $29, $c
  .db $e7
  .db $d, $29, $9, $18
  .db $e3
  .db $d, $21, $c, $1d
  .db $e3
  .db $5, $22, $c
  .db $e3
  .db $5, $22, $9
  .db $e3
  .db $5, $23, $c
  .db $fe
  .db $f5


;......................................
.pattern.table.chan3.pattern1

  .db $f8
  .db $e0
  .db $fe
  .db $fe
  .db $eb


;......................................
.pattern.table.chan3.pattern2

  .db $e0
  .db $fe
  .db $fe
  .db $fe
  .db $e5


;......................................
.pattern.table.chan3.pattern3

  .db $31, $e0, $8, $fd
  .db $eb
  .db $3d, $30, $d, $1b, $10, $8
  .db $e5
  .db $e0
  .db $e1
  .db $5, $30, $d
  .db $e3
  .db $e0
  .db $eb
  .db $5, $30, $d
  .db $eb
  .db $e0
  .db $e5
  .db $5, $28, $d
  .db $e2
  .db $5, $2b, $d
  .db $e2
  .db $5, $30, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $30, $d
  .db $e3
  .db $e0
  .db $eb
  .db $5, $30, $d
  .db $eb


;......................................
.pattern.table.chan3.pattern4

  .db $e0
  .db $eb
  .db $3d, $30, $d, $1b, $10, $8
  .db $e5
  .db $e0
  .db $e1
  .db $5, $30, $d
  .db $e3
  .db $e0
  .db $eb
  .db $5, $30, $d
  .db $eb
  .db $e0
  .db $e5
  .db $5, $2a, $d
  .db $e2
  .db $5, $2d, $d
  .db $e2
  .db $5, $30, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $30, $d
  .db $e3
  .db $e0
  .db $eb
  .db $5, $30, $d
  .db $eb


;......................................
.pattern.table.chan3.pattern5

  .db $e0
  .db $eb
  .db $5, $30, $d
  .db $e7
  .db $e0
  .db $e3
  .db $5, $31, $d
  .db $e7
  .db $e0
  .db $e3
  .db $5, $32, $d
  .db $e7
  .db $e0
  .db $eb
  .db $5, $37, $d
  .db $e3
  .db $e0
  .db $eb
  .db $5, $37, $d
  .db $eb
  .db $e0
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan4.pattern0

  .db $fe
  .db $fe
  .db $fe
  .db $e6


;......................................
.pattern.table.chan4.pattern1

  .db $30, $8, $fd
  .db $eb
  .db $3d, $29, $d, $1a, $10, $8
  .db $e5
  .db $e0
  .db $e1
  .db $5, $29, $d
  .db $e3
  .db $e0
  .db $fe
  .db $e5
  .db $5, $28, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $28, $d
  .db $e3
  .db $e0
  .db $f7


;......................................
.pattern.table.chan4.pattern2

  .db $ec
  .db $5, $26, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $26, $d
  .db $e3
  .db $e0
  .db $fe
  .db $e5
  .db $5, $28, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $28, $d
  .db $e3
  .db $e0
  .db $f7


;......................................
.pattern.table.chan4.pattern3

  .db $ec
  .db $5, $29, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $29, $d
  .db $e3
  .db $e0
  .db $fe
  .db $e5
  .db $5, $2a, $d
  .db $e5
  .db $e0
  .db $e1
  .db $5, $2a, $d
  .db $e3
  .db $e0
  .db $f7


;......................................
.pattern.table.chan4.pattern4

  .db $ec
  .db $5, $2d, $d
  .db $e7
  .db $e0
  .db $ef
  .db $5, $2f, $d
  .db $e7
  .db $e0
  .db $eb
  .db $5, $2f, $d
  .db $e3
  .db $e0
  .db $eb
  .db $5, $2f, $d
  .db $eb
  .db $e0
  .db $eb


;........................................................................
;........................................................................

;......................................
.pattern.table.chan5.pattern0

  .db $75, $18, $0, $11, $0, $3, $8, $ff
  .db $40, $3, $f, $3
  .db $ea
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $eb
  .db $75, $26, $1, $11, $0, $3, $8, $ff
  .db $eb
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $ea
  .db $30, $d, $0
  .db $fe
  .db $f2


;......................................
.pattern.table.chan5.pattern1

  .db $75, $26, $1, $11, $0, $3, $8, $ff
  .db $40, $3, $f, $1
  .db $f6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $ef
  .db $75, $5, $2, $11, $0, $3, $8, $ff
  .db $35, $13, $3, $11, $1
  .db $e1
  .db $e0
  .db $35, $5, $2, $11, $0
  .db $35, $13, $3, $11, $1
  .db $e1
  .db $e0
  .db $35, $5, $2, $11, $0
  .db $35, $13, $3, $11, $1
  .db $f6
  .db $35, $5, $2, $11, $0
  .db $35, $13, $3, $11, $1
  .db $ee
  .db $75, $26, $1, $11, $0, $3, $8, $ff
  .db $e7


;......................................
.pattern.table.chan5.pattern2

  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $40, $3, $f, $3
  .db $ea
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $ee
  .db $75, $5, $2, $11, $0, $3, $8, $bf
  .db $35, $13, $3, $11, $1
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $e3
  .db $35, $18, $5, $11, $1
  .db $eb
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $ee
  .db $75, $5, $2, $11, $0, $3, $8, $bf
  .db $35, $13, $3, $11, $1
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $e3


;......................................
.pattern.table.chan5.pattern3

  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $40, $3, $f, $3
  .db $ea
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $ee
  .db $75, $5, $2, $11, $0, $3, $8, $bf
  .db $35, $13, $3, $11, $1
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $e3
  .db $35, $18, $5, $11, $1
  .db $eb
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $26, $1, $11, $0, $3, $8, $bf
  .db $e2
  .db $5, $4, $2
  .db $35, $11, $3, $11, $1
  .db $e2
  .db $75, $4, $2, $11, $0, $3, $8, $fd
  .db $35, $11, $3, $11, $1
  .db $e2
  .db $75, $4, $2, $11, $0, $3, $8, $bf
  .db $35, $11, $3, $11, $1
  .db $e2
  .db $75, $8, $2, $11, $0, $3, $8, $bf
  .db $35, $13, $3, $11, $1
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $e3


;......................................
.pattern.table.chan5.pattern4

  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $eb
  .db $5, $18, $5
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $11, $4, $3, $8, $bf
  .db $eb
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $5, $18, $5
  .db $e7
  .db $45, $11, $4, $3, $8, $9e
  .db $e3
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $11, $4, $3, $8, $bf
  .db $e7
  .db $35, $17, $1, $11, $0
  .db $e3
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $13, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $13, $1, $11, $0, $3, $8, $bf
  .db $e2


;......................................
.pattern.table.chan5.pattern5

  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $eb
  .db $5, $18, $5
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $11, $4, $3, $8, $bf
  .db $eb
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $5, $18, $5
  .db $e7
  .db $45, $1e, $4, $3, $8, $9e
  .db $e3
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $1e, $4, $3, $8, $bf
  .db $e7
  .db $35, $17, $1, $11, $0
  .db $e3
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $13, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $13, $1, $11, $0, $3, $8, $bf
  .db $e2


;......................................
.pattern.table.chan5.pattern6

  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $eb
  .db $5, $18, $5
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $1e, $4, $3, $8, $bf
  .db $eb
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $5, $18, $5
  .db $e7
  .db $45, $1e, $4, $3, $8, $9e
  .db $e3
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $1e, $4, $3, $8, $bf
  .db $e7
  .db $35, $17, $1, $11, $0
  .db $e3
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $13, $1, $11, $0, $3, $8, $bf
  .db $e6
  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $75, $13, $1, $11, $0, $3, $8, $bf
  .db $e2


;......................................
.pattern.table.chan5.pattern7

  .db $75, $18, $5, $11, $1, $3, $8, $d8
  .db $eb
  .db $5, $18, $5
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $45, $1e, $4, $3, $8, $bf
  .db $eb
  .db $45, $18, $5, $3, $8, $d8
  .db $e7
  .db $5, $18, $5
  .db $e3
  .db $5, $18, $5
  .db $eb
  .db $5, $18, $5
  .db $e7
  .db $75, $5, $2, $11, $0, $3, $8, $bf
  .db $35, $1f, $3, $11, $1
  .db $35, $5, $2, $11, $0
  .db $35, $1f, $3, $11, $1
  .db $35, $5, $2, $11, $0
  .db $35, $1f, $3, $11, $1
  .db $ea
  .db $35, $5, $2, $11, $0
  .db $35, $1f, $3, $11, $1
  .db $e6
  .db $35, $5, $2, $11, $0
  .db $35, $1f, $3, $11, $1
  .db $e1
  .db $30, $b, $2




