

;###########################################################################
.pattern.table
  .dw .pattern.table.chan0
  .dw .pattern.table.chan1
  .dw .pattern.table.chan2
  .dw .pattern.table.chan3
  .dw .pattern.table.chan4
  .dw .pattern.table.chan5


;.....................................................
.pattern.table.chan0
  .dw .pattern.table.chan0.pattern0
  .dw .pattern.table.chan0.pattern1
  .dw .pattern.table.chan0.pattern2
  .dw .pattern.table.chan0.pattern3
  .dw .pattern.table.chan0.pattern4
  .dw .pattern.table.chan0.pattern5
  .dw .pattern.table.chan0.pattern6
  .dw .pattern.table.chan0.pattern7
  .dw .pattern.table.chan0.pattern8
  .dw .pattern.table.chan0.pattern9
  .dw .pattern.table.chan0.pattern10
  .dw .pattern.table.chan0.pattern11
  .dw .pattern.table.chan0.pattern12
  .dw .pattern.table.chan0.pattern13
  .dw .pattern.table.chan0.pattern14
  .dw .pattern.table.chan0.pattern15
;.....................................................
.pattern.table.chan1
  .dw .pattern.table.chan1.pattern0
  .dw .pattern.table.chan1.pattern1
  .dw .pattern.table.chan1.pattern2
  .dw .pattern.table.chan1.pattern3
  .dw .pattern.table.chan1.pattern4
  .dw .pattern.table.chan1.pattern5
  .dw .pattern.table.chan1.pattern6
  .dw .pattern.table.chan1.pattern7
  .dw .pattern.table.chan1.pattern8
  .dw .pattern.table.chan1.pattern9
  .dw .pattern.table.chan1.pattern10
;.....................................................
.pattern.table.chan2
  .dw .pattern.table.chan2.pattern0
  .dw .pattern.table.chan2.pattern1
  .dw .pattern.table.chan2.pattern2
  .dw .pattern.table.chan2.pattern3
  .dw .pattern.table.chan2.pattern4
  .dw .pattern.table.chan2.pattern5
  .dw .pattern.table.chan2.pattern6
  .dw .pattern.table.chan2.pattern7
  .dw .pattern.table.chan2.pattern8
  .dw .pattern.table.chan2.pattern9
;.....................................................
.pattern.table.chan3
  .dw .pattern.table.chan3.pattern0
  .dw .pattern.table.chan3.pattern1
  .dw .pattern.table.chan3.pattern2
  .dw .pattern.table.chan3.pattern3
  .dw .pattern.table.chan3.pattern4
  .dw .pattern.table.chan3.pattern5
  .dw .pattern.table.chan3.pattern6
  .dw .pattern.table.chan3.pattern7
  .dw .pattern.table.chan3.pattern8
  .dw .pattern.table.chan3.pattern9
  .dw .pattern.table.chan3.pattern10
  .dw .pattern.table.chan3.pattern11
  .dw .pattern.table.chan3.pattern12
  .dw .pattern.table.chan3.pattern13
  .dw .pattern.table.chan3.pattern14
  .dw .pattern.table.chan3.pattern15
  .dw .pattern.table.chan3.pattern16
  .dw .pattern.table.chan3.pattern17
  .dw .pattern.table.chan3.pattern18
  .dw .pattern.table.chan3.pattern19
  .dw .pattern.table.chan3.pattern20
;.....................................................
.pattern.table.chan4
  .dw .pattern.table.chan4.pattern0
;.....................................................
.pattern.table.chan5
  .dw .pattern.table.chan5.pattern0
  .dw .pattern.table.chan5.pattern1
  .dw .pattern.table.chan5.pattern2


;###########################################################################


;........................................................................
;........................................................................

;......................................
.pattern.table.chan0.pattern0

  .db $35, $9, $a, $10, $3
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $9, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $e, $a
  .db $e1
  .db $35, $10, $a, $3, $f
  .db $e8
  .db $30, $ec, $2
  .db $5, $e, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern1

  .db $5, $9, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $9, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $9, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $4, $a
  .db $eb
  .db $5, $6, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern2

  .db $5, $7, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $7, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $13, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $12, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $9, $a
  .db $e1
  .db $35, $b, $a, $3, $1f
  .db $e8
  .db $30, $ec, $2
  .db $5, $9, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $7, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern3

  .db $5, $c, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $c, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $18, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $18, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $17, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $18, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $18, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $12, $a
  .db $e1
  .db $35, $13, $a, $3, $1f
  .db $e8
  .db $30, $ec, $2
  .db $5, $10, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $c, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern4

  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $17, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $15, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $10, $a
  .db $e1
  .db $35, $12, $a, $3, $1f
  .db $e8
  .db $30, $ec, $2
  .db $5, $e, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $b, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern5

  .db $5, $a, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $a, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $16, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $14, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $f, $a
  .db $e1
  .db $35, $11, $a, $3, $1f
  .db $e8
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $a, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern6

  .db $5, $9, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $9, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $15, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $13, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $a
  .db $e1
  .db $e0
  .db $e5
  .db $5, $e, $a
  .db $e1
  .db $35, $10, $a, $3, $1f
  .db $e8
  .db $30, $ec, $2
  .db $5, $c, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $9, $a
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern7

  .db $5, $e, $a
  .db $ea
  .db $30, $ec, $2
  .db $5, $e, $a
  .db $ea
  .db $30, $ec, $2
  .db $5, $e, $a
  .db $e6
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e1
  .db $e0
  .db $e1
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $ee
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern8

  .db $5, $10, $a
  .db $e5
  .db $8, $1b
  .db $e5
  .db $8, $1a
  .db $e5
  .db $8, $19
  .db $e5
  .db $8, $18
  .db $e5
  .db $8, $17
  .db $e5
  .db $8, $16
  .db $e5
  .db $8, $15
  .db $e5
  .db $8, $14
  .db $e5
  .db $8, $13
  .db $e5
  .db $8, $12
  .db $e3


;......................................
.pattern.table.chan0.pattern9

  .db $e2
  .db $8, $11
  .db $e5
  .db $8, $10
  .db $e5
  .db $8, $f
  .db $e5
  .db $8, $e
  .db $e5
  .db $8, $d
  .db $e5
  .db $8, $c
  .db $e5
  .db $8, $b
  .db $e5
  .db $8, $a
  .db $e5
  .db $8, $9
  .db $e5
  .db $8, $8
  .db $e5
  .db $8, $7
  .db $e1


;......................................
.pattern.table.chan0.pattern10

  .db $e0
  .db $e3
  .db $d, $e, $a, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $13, $a
  .db $e3
  .db $e0
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $10, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $16, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1a, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $a
  .db $e6
  .db $30, $ec, $2
  .db $5, $1f, $a
  .db $e6
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern11

  .db $5, $21, $a
  .db $e3
  .db $35, $1f, $a, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1f, $a
  .db $e3
  .db $35, $1e, $a, $3, $1f
  .db $e2
  .db $30, $ec, $2
  .db $5, $1a, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $a
  .db $e6
  .db $30, $ec, $2
  .db $5, $13, $a
  .db $e6
  .db $30, $ec, $2
  .db $5, $10, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $e, $a
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern12

  .db $5, $10, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $4, $a
  .db $ef
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e7
  .db $8, $18
  .db $e7
  .db $8, $17
  .db $e3
  .db $e0
  .db $e3


;......................................
.pattern.table.chan0.pattern13

  .db $e4
  .db $d, $1a, $a, $1f
  .db $e3
  .db $e0
  .db $e3
  .db $5, $1c, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $15, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $16, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $17, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1a, $a
  .db $e3
  .db $e0
  .db $e3
  .db $5, $1e, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1c, $a
  .db $e2
  .db $30, $ec, $2
  .db $5, $1a, $a
  .db $e6
  .db $30, $ec, $2
  .db $5, $13, $a
  .db $e6
  .db $30, $ec, $2
  .db $5, $b, $a
  .db $e2
  .db $30, $ec, $2


;......................................
.pattern.table.chan0.pattern14

  .db $5, $4, $a
  .db $ef
  .db $8, $1b
  .db $e7
  .db $8, $1a
  .db $e7
  .db $8, $19
  .db $e7
  .db $8, $18
  .db $e7
  .db $8, $17
  .db $e7
  .db $8, $16
  .db $e7


;......................................
.pattern.table.chan0.pattern15

  .db $8, $15
  .db $e7
  .db $8, $14
  .db $e7
  .db $8, $13
  .db $e7
  .db $8, $12
  .db $e7
  .db $8, $11
  .db $e7
  .db $8, $10
  .db $e7
  .db $d, $4, $a, $1f
  .db $e2
  .db $30, $ec, $1
  .db $5, $5, $a
  .db $e2
  .db $30, $ec, $1
  .db $5, $6, $a
  .db $e2
  .db $30, $ec, $1
  .db $5, $7, $a
  .db $e2
  .db $30, $ec, $1


;........................................................................
;........................................................................

;......................................
.pattern.table.chan1.pattern0

  .db $7d, $23, $7, $1b, $10, $4, $3, $8, $fe
  .db $e3
  .db $5, $23, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $21, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $1e, $7
  .db $e3
  .db $e0
  .db $eb
  .db $5, $28, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $26, $7
  .db $eb


;......................................
.pattern.table.chan1.pattern1

  .db $5, $23, $7
  .db $e3
  .db $5, $23, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $21, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $1e, $7
  .db $e3
  .db $e0
  .db $f3
  .db $5, $23, $7
  .db $e3
  .db $5, $23, $7
  .db $e3
  .db $e0
  .db $e7


;......................................
.pattern.table.chan1.pattern2

  .db $5, $2a, $7
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan1.pattern3

  .db $35, $2e, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan1.pattern4

  .db $35, $2d, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan1.pattern5

  .db $35, $2c, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan1.pattern6

  .db $35, $2b, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan1.pattern7

  .db $35, $2f, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan1.pattern8

  .db $35, $30, $7, $4, $0
  .db $eb
  .db $5, $30, $7
  .db $eb
  .db $5, $30, $7
  .db $e7
  .db $5, $33, $7
  .db $e3
  .db $e0
  .db $eb
  .db $5, $33, $7
  .db $ef


;......................................
.pattern.table.chan1.pattern9

  .db $5, $32, $7
  .db $e7
  .db $5, $31, $8
  .db $35, $30, $8, $ed, $1
  .db $5, $2f, $8
  .db $35, $2e, $8, $ed, $1
  .db $d, $2d, $8, $1b
  .db $35, $2c, $8, $ed, $1
  .db $d, $2b, $8, $18
  .db $35, $2a, $8, $ed, $1
  .db $d, $29, $8, $14
  .db $35, $28, $8, $ed, $1
  .db $d, $27, $8, $f
  .db $35, $26, $8, $ed, $1
  .db $e1
  .db $e0
  .db $fe
  .db $ec


;......................................
.pattern.table.chan1.pattern10

  .db $fe
  .db $fe
  .db $e4


;........................................................................
;........................................................................

;......................................
.pattern.table.chan2.pattern0

  .db $7d, $28, $7, $1b, $10, $4, $3, $8, $ef
  .db $e3
  .db $5, $28, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $23, $7
  .db $e3
  .db $e0
  .db $eb
  .db $5, $2c, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $2a, $7
  .db $eb


;......................................
.pattern.table.chan2.pattern1

  .db $5, $28, $7
  .db $e3
  .db $5, $28, $7
  .db $e3
  .db $e0
  .db $e3
  .db $5, $26, $7
  .db $e3
  .db $e0
  .db $e7
  .db $5, $23, $7
  .db $e3
  .db $e0
  .db $f3
  .db $5, $2f, $7
  .db $e3
  .db $5, $2f, $7
  .db $e3
  .db $e0
  .db $e7


;......................................
.pattern.table.chan2.pattern2

  .db $5, $2f, $7
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan2.pattern3

  .db $35, $32, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan2.pattern4

  .db $35, $31, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan2.pattern5

  .db $35, $30, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan2.pattern6

  .db $35, $34, $7, $4, $0
  .db $e7
  .db $30, $4, $63
  .db $fe
  .db $f9


;......................................
.pattern.table.chan2.pattern7

  .db $35, $34, $7, $4, $0
  .db $eb
  .db $5, $34, $7
  .db $eb
  .db $5, $34, $7
  .db $e7
  .db $5, $37, $7
  .db $e3
  .db $e0
  .db $eb
  .db $5, $37, $7
  .db $ef


;......................................
.pattern.table.chan2.pattern8

  .db $5, $36, $7
  .db $e7
  .db $5, $35, $8
  .db $35, $34, $8, $ed, $1
  .db $5, $33, $8
  .db $35, $32, $8, $ed, $1
  .db $d, $31, $8, $1b
  .db $35, $30, $8, $ed, $1
  .db $d, $2f, $8, $18
  .db $35, $2e, $8, $ed, $1
  .db $d, $2d, $8, $14
  .db $35, $2c, $8, $ed, $1
  .db $d, $2b, $8, $f
  .db $35, $2a, $8, $ed, $1
  .db $e1
  .db $e0
  .db $fe
  .db $ec


;......................................
.pattern.table.chan2.pattern9

  .db $fe
  .db $fe
  .db $e4


;........................................................................
;........................................................................

;......................................
.pattern.table.chan3.pattern0

  .db $fe
  .db $fe
  .db $e4


;......................................
.pattern.table.chan3.pattern1

  .db $e4
  .db $3d, $2a, $6, $1e, $10, $5
  .db $35, $2c, $6, $3, $6
  .db $e9
  .db $30, $ec, $2
  .db $5, $2a, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $23, $6, $1e
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $28, $6, $1e
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $28, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $26, $6, $1e
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $23, $6, $1e
  .db $e3


;......................................
.pattern.table.chan3.pattern2

  .db $8, $14
  .db $e3
  .db $d, $26, $6, $1e
  .db $ea
  .db $30, $ec, $2
  .db $5, $28, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $29, $6, $1e
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $28, $6, $1e
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $23, $6, $1e
  .db $e3
  .db $8, $14
  .db $eb
  .db $e0
  .db $e3


;......................................
.pattern.table.chan3.pattern3

  .db $e4
  .db $3d, $2a, $6, $1e, $10, $5
  .db $35, $2c, $6, $3, $6
  .db $e9
  .db $30, $ec, $2
  .db $5, $2a, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $23, $6, $1e
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $28, $6, $1e
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $28, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $2a, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $26, $6, $1e
  .db $e2
  .db $30, $ec, $2
  .db $5, $23, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $21, $6
  .db $e3


;......................................
.pattern.table.chan3.pattern4

  .db $5, $23, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $28, $6, $1e
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $2a, $6, $1e
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $6
  .db $ef
  .db $30, $2, $8
  .db $e3
  .db $e0
  .db $ef


;......................................
.pattern.table.chan3.pattern5

  .db $5, $23, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $26, $6
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $28, $6, $1e
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $2a, $6, $1e
  .db $e2
  .db $30, $ec, $2
  .db $5, $2d, $6
  .db $e2
  .db $30, $ec, $2
  .db $5, $2f, $6
  .db $ef
  .db $30, $2, $8
  .db $e3
  .db $31, $e0, $2, $0
  .db $e3
  .db $3d, $2f, $9, $1d, $10, $6
  .db $e3
  .db $5, $31, $9
  .db $e3
  .db $5, $32, $9
  .db $e3


;......................................
.pattern.table.chan3.pattern6

  .db $5, $34, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $32, $9, $1d
  .db $e3
  .db $8, $14
  .db $e7
  .db $d, $2f, $9, $1d
  .db $e3
  .db $8, $14
  .db $e7
  .db $d, $2d, $9, $1d
  .db $e7
  .db $8, $14
  .db $e3
  .db $d, $2a, $9, $1d
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $26, $9
  .db $e7


;......................................
.pattern.table.chan3.pattern7

  .db $5, $28, $9
  .db $f3
  .db $8, $14
  .db $e3
  .db $d, $2a, $9, $1d
  .db $e3
  .db $5, $28, $9
  .db $fe
  .db $e1
  .db $8, $14
  .db $e3


;......................................
.pattern.table.chan3.pattern8

  .db $e0
  .db $e3
  .db $d, $25, $9, $1d
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $2d, $9, $1d
  .db $eb
  .db $5, $2a, $9
  .db $e7
  .db $8, $14
  .db $e3
  .db $d, $28, $9, $1d
  .db $e7
  .db $8, $14
  .db $e3
  .db $d, $26, $9, $1d
  .db $e7


;......................................
.pattern.table.chan3.pattern9

  .db $5, $24, $9
  .db $ef
  .db $8, $14
  .db $e3
  .db $d, $26, $9, $1d
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $24, $9
  .db $fe
  .db $e1
  .db $8, $14
  .db $e3


;......................................
.pattern.table.chan3.pattern10

  .db $e0
  .db $e7
  .db $d, $1f, $9, $1d
  .db $e3
  .db $5, $20, $9
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $21, $9, $1d
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $23, $9, $1d
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $5, $26, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e7
  .db $5, $28, $9
  .db $e3
  .db $5, $24, $9
  .db $e7


;......................................
.pattern.table.chan3.pattern11

  .db $5, $26, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2a, $9
  .db $e3
  .db $5, $2d, $9
  .db $e3
  .db $5, $2f, $9
  .db $e3
  .db $5, $32, $9
  .db $e3
  .db $8, $14
  .db $e3
  .db $d, $29, $9, $1d
  .db $e7
  .db $5, $28, $9
  .db $e7
  .db $5, $26, $9
  .db $e3
  .db $5, $23, $9
  .db $eb
  .db $8, $14
  .db $e3


;......................................
.pattern.table.chan3.pattern12

  .db $d, $24, $9, $1d
  .db $e3
  .db $5, $23, $9
  .db $e3
  .db $5, $24, $9
  .db $e3
  .db $5, $26, $9
  .db $e7
  .db $5, $24, $9
  .db $e3
  .db $5, $28, $9
  .db $e3
  .db $5, $2b, $9
  .db $e3
  .db $5, $2f, $9
  .db $e7
  .db $8, $14
  .db $e3
  .db $d, $2d, $9, $1d
  .db $e7
  .db $8, $14
  .db $e3
  .db $d, $2b, $9, $1d
  .db $e7


;......................................
.pattern.table.chan3.pattern13

  .db $5, $2b, $9
  .db $e1
  .db $35, $2d, $9, $3, $1
  .db $fd
  .db $5, $2f, $9
  .db $e3
  .db $5, $32, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $5, $32, $9
  .db $e3
  .db $5, $37, $9
  .db $e3
  .db $5, $34, $9
  .db $e3
  .db $5, $32, $9
  .db $e3
  .db $5, $34, $9
  .db $e3


;......................................
.pattern.table.chan3.pattern14

  .db $d, $34, $9, $14
  .db $e7
  .db $d, $34, $9, $1c
  .db $e7
  .db $d, $34, $9, $1b
  .db $e7
  .db $d, $34, $9, $1a
  .db $e7
  .db $d, $34, $9, $18
  .db $e7
  .db $d, $34, $9, $16
  .db $e7
  .db $d, $34, $9, $14
  .db $e7
  .db $d, $34, $9, $12
  .db $e7


;......................................
.pattern.table.chan3.pattern15

  .db $e0
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $d, $25, $5, $18
  .db $e3
  .db $3d, $20, $5, $1d, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $d, $20, $5, $18
  .db $e3
  .db $d, $20, $5, $1d
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e2
  .db $35, $20, $5, $ed, $1
  .db $e1
  .db $35, $20, $5, $ed, $2
  .db $e2
  .db $35, $1a, $5, $8, $fd
  .db $e3
  .db $5, $1a, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern16

  .db $d, $1a, $5, $18
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $d, $20, $5, $18
  .db $e3
  .db $3d, $20, $5, $1d, $8, $ee
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $d, $25, $5, $18
  .db $e3
  .db $3d, $20, $5, $1d, $8, $ee
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $35, $1a, $5, $8, $fd
  .db $e3
  .db $5, $1a, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern17

  .db $d, $1a, $5, $18
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $d, $25, $5, $18
  .db $e3
  .db $3d, $20, $5, $1d, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $d, $20, $5, $18
  .db $e3
  .db $d, $20, $5, $1d
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e2
  .db $35, $20, $5, $ed, $1
  .db $e1
  .db $35, $20, $5, $ed, $1
  .db $e2
  .db $35, $1a, $5, $8, $fd
  .db $e3
  .db $5, $1a, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern18

  .db $d, $1a, $5, $18
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $d, $25, $5, $18
  .db $e3
  .db $3d, $20, $5, $1d, $8, $ee
  .db $e2
  .db $35, $20, $5, $ed, $1
  .db $e1
  .db $35, $20, $5, $ed, $2
  .db $e2
  .db $d, $20, $5, $18
  .db $e3
  .db $d, $20, $5, $1d
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $35, $1a, $5, $8, $fd
  .db $e3
  .db $5, $1a, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern19

  .db $d, $1a, $5, $18
  .db $e3
  .db $3d, $25, $5, $1d, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $35, $25, $5, $8, $df
  .db $e3
  .db $5, $25, $5
  .db $e3
  .db $35, $20, $5, $8, $ee
  .db $e3
  .db $5, $20, $5
  .db $e3
  .db $35, $1a, $5, $8, $fd
  .db $e3
  .db $5, $1a, $5
  .db $e3


;......................................
.pattern.table.chan3.pattern20

  .db $35, $25, $5, $8, $df
  .db $e4
  .db $35, $25, $5, $ed, $1
  .db $e5
  .db $5, $25, $5
  .db $e4
  .db $35, $20, $5, $8, $ee
  .db $e4
  .db $35, $20, $5, $ed, $1
  .db $e5
  .db $5, $20, $5
  .db $e4
  .db $35, $25, $5, $8, $df
  .db $e4
  .db $35, $25, $5, $ed, $1
  .db $e5
  .db $5, $25, $5
  .db $e4
  .db $35, $20, $5, $8, $e
  .db $e1
  .db $5, $20, $5
  .db $e1
  .db $5, $20, $5
  .db $e3
  .db $35, $1a, $5, $8, $fd
  .db $e3
  .db $5, $1a, $5
  .db $e3


;........................................................................
;........................................................................

;......................................
.pattern.table.chan4.pattern0

  .db $fe
  .db $fe
  .db $e4


;........................................................................
;........................................................................

;......................................
.pattern.table.chan5.pattern0

  .db $7d, $24, $0, $1f, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $3d, $24, $0, $1b, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $2, $1b, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $7d, $24, $0, $1f, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $3d, $24, $0, $1b, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $e3
  .db $45, $24, $4, $3, $8, $df
  .db $30, $11, $0
  .db $e2


;......................................
.pattern.table.chan5.pattern1

  .db $7d, $24, $0, $1f, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $3d, $24, $0, $1b, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $2, $1b, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $7d, $24, $0, $1f, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $3d, $24, $0, $1b, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $75, $24, $2, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $45, $24, $3, $3, $8, $fd
  .db $e3
  .db $45, $24, $4, $3, $8, $df
  .db $30, $11, $0
  .db $e2


;......................................
.pattern.table.chan5.pattern2

  .db $7d, $24, $0, $1f, $11, $1, $f, $8, $ff, $9, $1
  .db $75, $24, $1, $11, $0, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $3d, $24, $0, $1b, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $2
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $2, $1b, $11, $0, $c, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $40, $c, $9, $1
  .db $40, $c, $f, $3
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $0, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $75, $24, $3, $11, $1, $3, $8, $fd
  .db $e3
  .db $5, $24, $3
  .db $40, $c, $f, $2
  .db $e1
  .db $40, $c, $f, $3
  .db $7d, $24, $0, $1f, $11, $1, $3, $8, $ff
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $3d, $24, $0, $1b, $11, $1
  .db $35, $24, $1, $11, $0
  .db $e2
  .db $7d, $24, $3, $1f, $11, $1, $3, $8, $fd
  .db $e3
  .db $75, $24, $2, $11, $0, $f, $8, $ff, $9, $2
  .db $70, $11, $1, $c, $f, $1
  .db $35, $24, $2, $11, $0
  .db $70, $11, $1, $c, $f, $2
  .db $35, $24, $2, $11, $0
  .db $30, $11, $1
  .db $e2
  .db $35, $24, $2, $11, $0
  .db $30, $11, $1
  .db $e2
  .db $35, $24, $2, $11, $0
  .db $30, $11, $1
  .db $e2




