

;###########################################################################
.patternList.table
  .dw .patternList.chan0
  .dw .patternList.chan1
  .dw .patternList.chan2
  .dw .patternList.chan3
  .dw .patternList.chan4
  .dw .patternList.chan5

.patternList.chan0
  .db 0
.patternList.chan1
  .db 0
.patternList.chan2
  .db 0
.patternList.chan3
  .db 0
.patternList.chan4
  .db 0
.patternList.chan5
  .db 0


